import { FileKey2, Plus } from 'lucide-react';
import { useState } from 'react';
import type { VehicleDocumentMetadata } from './types';

const emptyDocument = (): Omit<VehicleDocumentMetadata, 'id' | 'createdAt' | 'source'> => ({ kind: 'other', label: '', documentReference: '', fileNameNote: '', effectiveOn: '', expiresOn: '', note: '' });

export function DocumentMetadataPanel({ documents, onAdd }: { documents: VehicleDocumentMetadata[]; onAdd: (document: Omit<VehicleDocumentMetadata, 'id' | 'createdAt' | 'source'>) => void }) {
  const [draft, setDraft] = useState(emptyDocument);
  const [open, setOpen] = useState(false);
  function submit(event: React.FormEvent) { event.preventDefault(); if (!draft.label.trim()) return; onAdd({ ...draft, label: draft.label.trim() }); setDraft(emptyDocument()); setOpen(false); }
  return <section className="vehicle-card document-metadata"><header><div><p className="eyebrow">Metadata only</p><h2>Vehicle documents</h2></div><FileKey2 aria-hidden/></header><p className="document-boundary">No document upload is available. Store only a safe label, reference note, and dates. Do not enter card data, credentials, or full sensitive document numbers.</p><div className="document-list">{documents.map((document) => <article key={document.id}><span><strong>{document.label}</strong><small>{document.kind.replaceAll('_', ' ')} · {document.source.replace('_', ' ')}</small></span><span><b>{document.expiresOn ? `Expires ${document.expiresOn}` : 'No expiry recorded'}</b><small>{document.documentReference || document.fileNameNote || 'No reference note'}</small></span></article>)}</div>
    <button type="button" className="button secondary" onClick={() => setOpen((value) => !value)}><Plus aria-hidden/>{open ? 'Close metadata form' : 'Add metadata'}</button>
    {open && <form onSubmit={submit}><label><span>Document kind</span><select value={draft.kind} onChange={(event) => setDraft({ ...draft, kind: event.target.value as VehicleDocumentMetadata['kind'] })}><option value="registration">Registration</option><option value="insurance">Insurance</option><option value="maintenance_record">Maintenance record</option><option value="receipt_reference">Receipt reference</option><option value="other">Other</option></select></label><label><span>Label</span><input required value={draft.label} onChange={(event) => setDraft({ ...draft, label: event.target.value })} placeholder="Safe document label"/></label><label><span>Reference note</span><input value={draft.documentReference} onChange={(event) => setDraft({ ...draft, documentReference: event.target.value })} placeholder="Do not enter a full sensitive number"/></label><label><span>File-name note</span><input value={draft.fileNameNote} onChange={(event) => setDraft({ ...draft, fileNameNote: event.target.value })} placeholder="Metadata text only"/></label><label><span>Effective date</span><input type="date" value={draft.effectiveOn} onChange={(event) => setDraft({ ...draft, effectiveOn: event.target.value })}/></label><label><span>Expiration date</span><input type="date" value={draft.expiresOn} onChange={(event) => setDraft({ ...draft, expiresOn: event.target.value })}/></label><label className="document-note-field"><span>Note</span><textarea rows={3} value={draft.note} onChange={(event) => setDraft({ ...draft, note: event.target.value })}/></label><button type="submit" className="button primary">Add local metadata</button></form>}
  </section>;
}
