import { BarChart3, MousePointerClick, Route, Users } from 'lucide-react';
import { useAnalytics, useRequests } from '../hooks';
import { StatePanel } from '../components/StatePanel';
import { serviceLabels } from '../components/RequestTable';
const pct=(value:number,total:number)=>total?`${Math.round(value/total*100)}%`:'—';
export function Analytics(){
  const analytics=useAnalytics(),requests=useRequests();
  if(analytics.loading||requests.loading)return <StatePanel kind="loading" title="Preparing business analytics"/>;
  if(analytics.error)return <StatePanel kind="error" title="Analytics could not be loaded" body={analytics.error} retry={analytics.reload}/>;
  if(requests.error)return <StatePanel kind="error" title="Ride totals could not be loaded" body={requests.error} retry={requests.reload}/>;
  const totals=analytics.data.daily.reduce((a,d)=>({views:a.views+d.pageViews,visitors:a.visitors+d.visitors,starts:a.starts+d.formStarts,submissions:a.submissions+d.submissions}),{views:0,visitors:0,starts:0,submissions:0});
  const quoteTotal=requests.data.reduce((n,r)=>n+(r.quoteAmount||0),0),paid=requests.data.filter(r=>r.paymentStatus==='paid').reduce((n,r)=>n+(r.quoteAmount||0),0),maxDay=Math.max(1,...analytics.data.daily.map(d=>d.pageViews));
  return <div className="page analytics-page"><header className="page-head"><div><p className="eyebrow">Pxpress intelligence</p><h1>Business analytics</h1><p>Website attention, request conversion, services, and money in one owner-only view.</p></div></header>
    <section className="analytics-hero" aria-label="Website performance summary"><div><Users aria-hidden/><strong>{totals.visitors}</strong><span>Visitors · 90 days</span></div><div><BarChart3 aria-hidden/><strong>{totals.views}</strong><span>Page views</span></div><div><MousePointerClick aria-hidden/><strong>{pct(totals.starts,totals.visitors)}</strong><span>Visitor to form</span></div><div><Route aria-hidden/><strong>{pct(totals.submissions,totals.starts)}</strong><span>Form completion</span></div></section>
    <section className="analytics-grid"><article className="analytics-card trend-card"><header><div><p className="eyebrow">Traffic</p><h2>Daily attention</h2></div><span>{analytics.data.daily.length} tracked days</span></header>{analytics.data.daily.length?<div className="spark-bars" aria-label="Daily page views">{analytics.data.daily.map(d=><div key={d.day} aria-label={`${d.day}: ${d.pageViews} page views`}><i aria-hidden style={{height:`${Math.max(5,d.pageViews/maxDay*100)}%`}}/><span>{new Date(`${d.day}T12:00:00`).toLocaleDateString('en-US',{month:'short',day:'numeric'})}</span></div>)}</div>:<p className="empty-copy">Analytics begin after the updated website is deployed.</p>}</article>
      <article className="analytics-card"><header><div><p className="eyebrow">Request funnel</p><h2>From visit to request</h2></div></header><div className="funnel"><div><span>Visitors</span><strong>{totals.visitors}</strong><i style={{width:'100%'}}/></div><div><span>Form starts</span><strong>{totals.starts}</strong><i style={{width:totals.visitors?pct(totals.starts,totals.visitors):'0%'}}/></div><div><span>Submitted</span><strong>{totals.submissions}</strong><i style={{width:totals.visitors?pct(totals.submissions,totals.visitors):'0%'}}/></div></div></article>
      <article className="analytics-card"><header><div><p className="eyebrow">Services</p><h2>What guests choose</h2></div></header><div className="rank-list">{analytics.data.services.map(row=><div key={row.service}><span>{serviceLabels[row.service]}</span><strong>{row.selections} selected · {row.submissions} submitted</strong></div>)}{!analytics.data.services.length&&<p className="empty-copy">No service activity yet.</p>}</div></article>
      <article className="analytics-card"><header><div><p className="eyebrow">Acquisition</p><h2>Where visits begin</h2></div></header><div className="rank-list">{analytics.data.sources.map(row=><div key={row.source}><span>{row.source}</span><strong>{row.sessions} sessions · {row.submissions} requests</strong></div>)}{!analytics.data.sources.length&&<p className="empty-copy">No traffic sources yet.</p>}</div></article>
      <article className="analytics-card"><header><div><p className="eyebrow">Pages</p><h2>Most viewed</h2></div></header><div className="rank-list">{analytics.data.pages.map(row=><div key={row.pageKey}><span>{row.pageKey==='area'?'Where we operate':row.pageKey}</span><strong>{row.pageViews} views · {row.ctaClicks} actions</strong></div>)}{!analytics.data.pages.length&&<p className="empty-copy">No page activity yet.</p>}</div></article>
      <article className="analytics-card money-card"><header><div><p className="eyebrow">Business</p><h2>Requests and revenue</h2></div></header><dl><div><dt>Total requests</dt><dd>{requests.data.length}</dd></div><div><dt>Quotes created</dt><dd>{requests.data.filter(r=>r.quoteAmount!==undefined).length}</dd></div><div><dt>Quoted value</dt><dd>${quoteTotal.toLocaleString()}</dd></div><div><dt>Recorded paid</dt><dd>${paid.toLocaleString()}</dd></div></dl></article>
    </section><p className="analytics-privacy">First-party analytics only. Names, addresses, phone numbers, email addresses, full URLs, and IP addresses are not stored in website analytics.</p></div>;
}
