import { Download, Search, Trash2 } from 'lucide-react';
import { useState } from 'react';
import { Link } from 'react-router-dom';
import { StatePanel } from '../components/StatePanel';import { useRequests } from '../hooks';import { toCustomers } from '../lib/selectors';
import { removeCustomerContact } from '../lib/repository';
import { csvRows } from '../lib/csv';
import type { Customer } from '../types';
export const customersToCsv=(customers:Customer[])=>csvRows([['Name','Email','Phone','Requests','Last ride','Quoted'],...customers.map(c=>[c.name,c.email,c.phone,c.rides,c.lastRide,c.totalQuoted])]);
export function Customers(){const {data,loading,error,reload}=useRequests(),[query,setQuery]=useState(''),[sort,setSort]=useState('name'),[deleting,setDeleting]=useState(''),[message,setMessage]=useState(''),[messageKind,setMessageKind]=useState<'status'|'alert'>('status');const customers=toCustomers(data),filtered=customers.filter(c=>`${c.name} ${c.email} ${c.phone}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>sort==='recent'?b.lastRide.localeCompare(a.lastRide):sort==='rides'?b.rides-a.rides||a.name.localeCompare(b.name):a.name.localeCompare(b.name));
function exportCustomers(){const blob=new Blob([customersToCsv(filtered)],{type:'text/csv;charset=utf-8'});const link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download=`pxpress-customers-${new Date().toISOString().slice(0,10)}.csv`;link.click();URL.revokeObjectURL(link.href);}
async function deleteContact(customer:{id:string;name:string}){if(!window.confirm(`Remove ${customer.name} from the customer directory? Their name, email, and phone will be erased. Ride history remains as an anonymized operational record.`))return;setDeleting(customer.id);setMessage('');try{await removeCustomerContact(customer.id);setMessageKind('status');setMessage(`${customer.name} was removed from the customer directory.`);reload()}catch(e){setMessageKind('alert');setMessage(e instanceof Error?e.message:'Contact could not be removed.')}finally{setDeleting('')}}
return <div className="page compact-guests"><header className="page-head"><h1>Guests</h1><button type="button" className="desk-icon-action" onClick={exportCustomers} disabled={!filtered.length} aria-label="Export guests"><Download aria-hidden/></button></header>
<div className="guest-list-tools"><label className="guest-finder-search"><Search aria-hidden/><input aria-label="Search customers" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Name, email or phone"/></label><select aria-label="Sort guests" value={sort} onChange={e=>setSort(e.target.value)}><option value="name">Name A–Z</option><option value="recent">Most recent ride</option><option value="rides">Most rides</option></select></div>
{message&&<p role={messageKind}>{message}</p>}
{loading?<StatePanel kind="loading" title="Loading guests"/>:error?<StatePanel kind="error" title="Guests unavailable" body={error} retry={reload}/>:<ul className="compact-guest-list">{filtered.map(c=><li key={c.id}><Link to={`/customers/${encodeURIComponent(c.id)}`} aria-label={`View guest profile for ${c.name}`}><span className="guest-finder-initials" aria-hidden>{c.name.split(' ').map(n=>n[0]).join('').slice(0,2)}</span><span><strong>{c.name}</strong><small>{c.phone||c.email}</small></span><small>{c.rides} ride{c.rides===1?'':'s'}</small></Link><button type="button" disabled={deleting===c.id} onClick={()=>deleteContact(c)} aria-label={`Delete contact for ${c.name}`}><Trash2 aria-hidden/></button></li>)}{!filtered.length&&<li className="guest-finder-empty">No matching guests</li>}</ul>}</div>}
