import { ArrowLeft,CheckCircle2,ChevronRight,Clock3,Gauge,Info,LocateFixed,Mail,MapPin,Navigation,Pause,Phone,RotateCcw,ShieldCheck,Users,X } from 'lucide-react';
import { useCallback,useEffect,useRef,useState } from 'react';
import { Link,useParams } from 'react-router-dom';
import { StatePanel } from '../components/StatePanel';
import { serviceLabels,statusLabels } from '../components/RequestTable';
import { createDriveSession,isStaleDriveSession,recordManualMileage,segmentElapsedMinutes,segmentMiles,totalActualMiles,transitionDriveSession,type DriveAction,type DriveSegmentKind,type DriveSession } from '../features/drive-mode/domain';
import { DriveDirectionsChooser } from '../features/drive-mode/DriveDirectionsChooser';
import { PlaceDisplay } from '../features/places/PlaceDisplay';
import { clearDriveSession,loadDriveSession,saveDriveSession } from '../features/drive-mode/storage';
import { useForegroundLocation } from '../features/drive-mode/useForegroundLocation';
import { driveNavigationTarget,navigationStopsForRequest,navigationUrl,readNavigationProvider,saveNavigationProvider,type NavigationProvider } from '../features/navigation/navigation';
import { useRequests } from '../hooks';
import { completePaidRide,transitionRequest } from '../lib/repository';
import { formatDate,formatDateTime,formatTime } from '../lib/selectors';
import type { RideRequest } from '../types';

const baseAddress='10273 Maryland St, Reminderville, OH 44202';
const stageCopy:Record<DriveSession['stage'],{label:string;eyebrow:string}>={
 ready:{label:'Ready to leave',eyebrow:'Next · Pickup'},heading_to_pickup:{label:'Heading to pickup',eyebrow:'Active · Pickup leg'},at_pickup:{label:'At pickup',eyebrow:'Next · Guest onboard'},passenger_onboard:{label:'Passenger onboard',eyebrow:'Active · Outbound guest leg'},at_destination:{label:'At outbound destination',eyebrow:'Outbound leg complete'},return_passenger_onboard:{label:'Booked return underway',eyebrow:'Active · Return guest leg'},at_return_stop:{label:'Booked ride complete',eyebrow:'Choose what is next'},returning_to_base:{label:'Returning to base',eyebrow:'Active · Base return'},completed_elsewhere:{label:'Continuing elsewhere',eyebrow:'Drive session complete'},at_base:{label:'Back at base',eyebrow:'Drive session complete'},
};
const segmentLabels:Record<DriveSegmentKind,string>={start_to_pickup:'Start to pickup',pickup_to_destination:'Pickup to outbound destination',destination_to_return:'Outbound destination to booked return stop',final_to_base:'Final stop to base'};
const eventId=(action:string)=>`${action}:${Date.now()}:${crypto.randomUUID()}`;

function ManualMileageEditor({session,onSave}:{session:DriveSession;onSave:(kind:DriveSegmentKind,input:{miles?:number;startOdometer?:number;endOdometer?:number;reason:string})=>void}){
 const kinds=Object.keys(session.segments) as DriveSegmentKind[];
 const [kind,setKind]=useState<DriveSegmentKind>(kinds.at(-1)||'start_to_pickup'),[method,setMethod]=useState<'segment'|'odometer'>('segment'),[miles,setMiles]=useState(''),[start,setStart]=useState(''),[end,setEnd]=useState(''),[reason,setReason]=useState(''),[error,setError]=useState('');
 useEffect(()=>{if(!session.segments[kind]&&kinds.length)setKind(kinds.at(-1)!)},[kind,kinds,session.segments]);
 function submit(e:React.FormEvent){e.preventDefault();setError('');try{onSave(kind,{miles:method==='segment'?Number(miles):undefined,startOdometer:method==='odometer'?Number(start):undefined,endOdometer:method==='odometer'?Number(end):undefined,reason});setMiles('');setStart('');setEnd('');setReason('')}catch(value){setError(value instanceof Error?value.message:'Manual mileage could not be saved.')}}
 if(!kinds.length)return <p className="drive-muted">Start a route segment before entering manual mileage.</p>;
 return <form className="manual-mileage" onSubmit={submit}>
  <div className="drive-form-grid"><label>Route segment<select value={kind} onChange={event=>setKind(event.target.value as DriveSegmentKind)}>{kinds.map(value=><option key={value} value={value}>{segmentLabels[value]}</option>)}</select></label><fieldset><legend>Entry method</legend><label><input type="radio" name="mileage-method" checked={method==='segment'} onChange={()=>setMethod('segment')}/> Segment miles</label><label><input type="radio" name="mileage-method" checked={method==='odometer'} onChange={()=>setMethod('odometer')}/> Odometer</label></fieldset></div>
  {method==='segment'?<label>Miles<input type="number" inputMode="decimal" min="0" max="1000" step="0.1" value={miles} onChange={event=>setMiles(event.target.value)} required/></label>:<div className="drive-form-grid"><label>Starting odometer<input type="number" inputMode="decimal" min="0" step="0.1" value={start} onChange={event=>setStart(event.target.value)} required/></label><label>Ending odometer<input type="number" inputMode="decimal" min="0" step="0.1" value={end} onChange={event=>setEnd(event.target.value)} required/></label></div>}
  <label>Reason for override<input value={reason} onChange={event=>setReason(event.target.value)} placeholder="GPS paused or odometer reading" minLength={3} required/></label>{error&&<p className="form-error" role="alert">{error}</p>}<button className="button secondary" type="submit"><Gauge aria-hidden/>Save manual mileage</button>
 </form>;
}

function RideDetails({request,session,onClose}:{request:RideRequest;session:DriveSession;onClose:()=>void}){
 const closeRef=useRef<HTMLButtonElement>(null),sheetRef=useRef<HTMLElement>(null);
 useEffect(()=>{const overflow=document.body.style.overflow;document.body.style.overflow='hidden';closeRef.current?.focus();const keydown=(event:KeyboardEvent)=>{if(event.key==='Escape'){onClose();return}if(event.key!=='Tab'||!sheetRef.current)return;const items=[...sheetRef.current.querySelectorAll<HTMLElement>('button:not([disabled]),a[href],input:not([disabled]),select:not([disabled]),summary')];if(!items.length)return;const first=items[0],last=items.at(-1)!;if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus()}};document.addEventListener('keydown',keydown);return()=>{document.removeEventListener('keydown',keydown);document.body.style.overflow=overflow}},[onClose]);
 return <div className="drive-sheet-backdrop" role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget)onClose()}}><section ref={sheetRef} className="drive-sheet" role="dialog" aria-modal="true" aria-labelledby="drive-details-title">
  <header><div><p className="eyebrow">{request.requestNumber}</p><h2 id="drive-details-title">Ride details</h2></div><button ref={closeRef} type="button" className="icon-button" onClick={onClose} aria-label="Close ride details"><X aria-hidden/></button></header>
  <div className="drive-sheet-body"><section><h3>Schedule</h3><dl><div><dt>Pickup</dt><dd>{formatDate(request.pickupDate)} at {formatTime(request.pickupTime)}</dd></div>{request.returnDate&&<div><dt>Booked return</dt><dd>{formatDate(request.returnDate)} at {formatTime(request.returnTime||'')}</dd></div>}<div><dt>Service</dt><dd>{serviceLabels[request.service]}</dd></div></dl></section><section><h3>Guest</h3><strong>{request.customerName}</strong>{!request.customerDeleted&&<div className="drive-contact-row"><a className="button secondary" href={`tel:${request.phone}`}><Phone aria-hidden/>Call</a><a className="button secondary" href={`mailto:${request.email}`}><Mail aria-hidden/>Email</a></div>}</section><section><h3>Route</h3><ol className="drive-detail-route"><li><span>Pickup</span><PlaceDisplay request={request} kind="pickup"/></li><li><span>Outbound destination</span><PlaceDisplay request={request} kind="destination"/></li>{request.returnAddress&&<li><span>Booked return stop</span><PlaceDisplay request={request} kind="return"/></li>}</ol></section><section><h3>Ride notes</h3><dl><div><dt>Passengers</dt><dd>{request.passengers}</dd></div><div><dt>Luggage</dt><dd>{request.carryons} carry-on · {request.checkedBags} checked</dd></div>{request.hasOversizedItems&&<div><dt>Oversized item</dt><dd>{request.oversizedDescription||'Reported by guest'}</dd></div>}</dl><p>{request.customerNotes||'No guest notes.'}</p></section><section><h3>Distance record</h3><p>{request.cachedRouteMiles!==undefined?`${request.cachedRouteMiles.toFixed(1)} estimated route miles`:'No cached route estimate.'}</p><p>{totalActualMiles(session).toFixed(1)} actual miles recorded in Drive Mode.</p>{(Object.keys(session.segments) as DriveSegmentKind[]).map(kind=><div className="drive-segment-line" key={kind}><span>{segmentLabels[kind]}</span><strong>{segmentMiles(session.segments[kind]).toFixed(1)} mi · {segmentElapsedMinutes(session.segments[kind])} min</strong></div>)}</section></div>
 </section></div>;
}

export function DriveMode(){
 const {id}=useParams(),requests=useRequests(),[session,setSessionState]=useState<DriveSession|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[storageError,setStorageError]=useState(''),[detailsOpen,setDetailsOpen]=useState(false),[preferredNavigationProvider,setPreferredNavigationProvider]=useState(readNavigationProvider),transitionLock=useRef(false),requestVersion=useRef(1),detailsButton=useRef<HTMLButtonElement>(null);
 const request=requests.data.find(item=>item.id===id);
 useEffect(()=>{if(!id)return;const stored=loadDriveSession(id);if(stored){setSessionState(stored);return}const initial=createDriveSession(id);setSessionState(initial);if(!saveDriveSession(initial))setStorageError('This browser is blocking Drive Mode storage. No ride status will change until storage works. Keep the page open and write down odometer readings for manual recovery.')},[id]);
 useEffect(()=>{if(request?.version)requestVersion.current=request.version},[request?.version]);
 const updateSession=useCallback((updater:(current:DriveSession)=>DriveSession)=>{setSessionState(current=>{if(!current)return current;const next=updater(current);if(!saveDriveSession(next)){setStorageError('This drive update could not be saved on this device. GPS was not recorded; pause and use an odometer note.');return current}setStorageError('');return next})},[]);
 const location=useForegroundLocation(session||createDriveSession(id||'pending','1970-01-01T00:00:00.000Z','pending'),updateSession);
 useEffect(()=>{if(storageError&&location.isWatching)location.stop('GPS paused because this device could not save the checkpoint.')},[location,storageError]);
 const closeDetails=useCallback(()=>{setDetailsOpen(false);requestAnimationFrame(()=>detailsButton.current?.focus())},[]);
 if(requests.loading||!session)return <StatePanel kind="loading" title="Opening Drive Mode"/>;
 if(requests.error)return <StatePanel kind="error" title="Drive Mode could not be loaded" body={requests.error} retry={requests.reload}/>;
 if(!request)return <div className="page drive-page"><Link className="drive-home-link" to="/"><ArrowLeft aria-hidden/> Back to Home</Link><StatePanel kind="empty" title="Ride not found"/></div>;
 const ride=request,driveSession=session,hasBookedReturn=Boolean(ride.returnAddress),bookedReturnIncomplete=/round/i.test(ride.tripType)&&!ride.returnAddress;
 const navigationTarget=driveNavigationTarget(ride,session.stage);
 const pickupStop=navigationStopsForRequest(ride).find(stop=>stop.kind==='pickup'),pickupDirections=pickupStop?navigationUrl(preferredNavigationProvider,pickupStop.address):null,copy=stageCopy[session.stage],actualMiles=totalActualMiles(session),estimate=ride.cachedRouteMiles;
 const paidOperationalStatus=ride.status==='confirmed'||ride.status==='in_progress'||(ride.status==='completed'&&['at_destination','at_return_stop','returning_to_base','completed_elsewhere','at_base'].includes(session.stage));
 const needsPickupDirections=session.stage==='ready';
 const driveBlockReason=busy?'Saving the previous drive step. Wait a moment.':ride.paymentStatus!=='paid'?'Payment is not verified yet. Confirm payment before starting this ride.':!paidOperationalStatus?`This ride is ${statusLabels[ride.status]||ride.status}. Confirm it before using Drive Mode.`:bookedReturnIncomplete?'This round trip is missing its return address. Add the return stop before driving.':storageError?'This phone cannot save Drive Mode yet. Allow site storage before starting.':needsPickupDirections&&!pickupDirections?'The pickup address is missing or invalid. Add a valid pickup before starting directions.':'';
 const canOperate=!driveBlockReason;

 async function advance(action:DriveAction,navigationOpened=false){
  if(transitionLock.current||busy)return;
  transitionLock.current=true;setBusy(true);setMessage('');
  const before=driveSession;
  try{
   const next=transitionDriveSession(before,action,eventId(action));
   if(!saveDriveSession(next)){setStorageError('This drive step could not be saved on this device. No request status was changed. Enable site storage or keep a written odometer/time note.');if(navigationOpened)setMessage('Directions opened, but the drive step was not saved. Return here and retry after allowing site storage.');return}
   setSessionState(next);setStorageError('');
   try{
    if(action==='start_heading'&&ride.status==='confirmed'){await transitionRequest(ride.id,requestVersion.current,'in_progress','Owner started heading to pickup from Drive Mode');requestVersion.current+=1;requests.reload()}
    const completesRide=(action==='arrive_destination'&&!hasBookedReturn)||action==='arrive_return_stop';
    if(completesRide&&ride.status!=='completed'){
     if(!window.confirm('Mark this paid booked ride complete?')){saveDriveSession(before);setSessionState(before);return}
     await completePaidRide({...ride,version:requestVersion.current},'auto');requestVersion.current+=1;requests.reload();
    }
   }catch(error){const rolledBack=saveDriveSession(before);setSessionState(before);if(!rolledBack)setStorageError('The request update failed and this device could not restore the prior checkpoint. Keep this page open and record the shown session summary.');throw error}
   if(action==='arrive_destination'||action==='arrive_return_stop')location.stop('Guest leg complete. Resume only if you choose another tracked segment.');
   if(action==='continue_elsewhere'||action==='arrive_base')location.stop('Drive session complete. GPS mileage is off.');
   setMessage(action==='arrive_destination'&&hasBookedReturn?'Outbound arrival saved. Start the booked return when the guest is onboard.':action==='arrive_destination'||action==='arrive_return_stop'?'Paid booked ride completed. Choose whether to return to base.':'Drive step saved on this device.');
  }catch(error){const detail=error instanceof Error?error.message:'That drive step could not be saved.';setMessage(navigationOpened?`Directions opened, but the drive step was not saved. Return here and retry. ${detail}`:detail)}finally{transitionLock.current=false;setBusy(false)}
 }
 function startHeadingToPickup(){
  if(!canOperate||!pickupDirections)return;
  window.open(pickupDirections,'_blank','noopener,noreferrer');
  void advance('start_heading',true);
 }
 function rememberNavigationProvider(provider:NavigationProvider){setPreferredNavigationProvider(provider);saveNavigationProvider(provider)}
 function saveManual(kind:DriveSegmentKind,input:{miles?:number;startOdometer?:number;endOdometer?:number;reason:string}){const next=recordManualMileage(driveSession,kind,input,eventId('manual-mileage'));if(!saveDriveSession(next)){setStorageError('Manual mileage could not be saved. Keep the odometer readings written down and retry after enabling site storage.');return}setSessionState(next);setStorageError('');setMessage('Manual mileage saved with an audit note.')}
 function resetLocal(){if(!window.confirm('Clear this device’s Drive Mode session for this ride? Request status and provider records will not change.'))return;if(!clearDriveSession(ride.id)){setStorageError('This device session could not be cleared. No data or request status was changed.');return}location.stop('GPS mileage is off.');const fresh=createDriveSession(ride.id);if(!saveDriveSession(fresh)){setStorageError('The old session was cleared, but a new device session could not be saved. Drive actions remain blocked.');setSessionState(fresh);return}setSessionState(fresh);setStorageError('');setMessage('This device’s Drive Mode session was cleared.')}
 const primary=session.stage==='ready'?{label:'Start heading to pickup',action:'start_heading' as const}:session.stage==='heading_to_pickup'?{label:'Arrived at pickup',action:'arrive_pickup' as const}:session.stage==='at_pickup'?{label:'Passenger onboard · Start ride',action:'passenger_onboard' as const}:session.stage==='passenger_onboard'?{label:hasBookedReturn?'Arrived at outbound destination':'Arrived at destination · Complete paid ride',action:'arrive_destination' as const}:session.stage==='at_destination'&&hasBookedReturn?{label:'Passenger onboard · Start booked return',action:'start_booked_return' as const}:session.stage==='return_passenger_onboard'?{label:'Arrived at booked return stop · Complete paid ride',action:'arrive_return_stop' as const}:session.stage==='returning_to_base'?{label:'Arrived at base',action:'arrive_base' as const}:null;
 const showAfterDropChoice=(session.stage==='at_destination'&&!hasBookedReturn)||session.stage==='at_return_stop';
 const bookedReturnDone=['at_return_stop','returning_to_base','completed_elsewhere','at_base'].includes(session.stage);
 const recoverySummary=JSON.stringify({requestNumber:ride.requestNumber,stage:session.stage,updatedAt:formatDateTime(session.updatedAt),segments:Object.fromEntries((Object.keys(session.segments) as DriveSegmentKind[]).map(kind=>[kind,{miles:segmentMiles(session.segments[kind]).toFixed(1),minutes:segmentElapsedMinutes(session.segments[kind])}]))},null,2);

 return <div className="page drive-page">
  <Link className="drive-home-link" to="/"><ArrowLeft aria-hidden/> Back to Home</Link>
  <header className="drive-command"><div><p className="eyebrow">Drive Mode · {ride.requestNumber}</p><h1>{copy.label}</h1><p>{serviceLabels[ride.service]} for {ride.customerName}</p></div><div className="drive-now"><span>{copy.eyebrow}</span><strong>{formatTime(ride.pickupTime)}</strong><small>{formatDate(ride.pickupDate)}</small></div></header>
  {isStaleDriveSession(session)&&<div className="drive-alert" role="alert"><Clock3 aria-hidden/><span><strong>Saved session needs review</strong>This device’s active session is over 24 hours old. Confirm the ride before continuing or clear the local session.</span></div>}
  {bookedReturnIncomplete&&<div className="drive-alert" role="alert"><ShieldCheck aria-hidden/><span><strong>Booked return address is missing</strong>Drive actions remain blocked so this round trip cannot be completed at the wrong stop. Open Ride details to review the request.</span></div>}
  {storageError&&<div className="drive-alert storage-alert" role="alert"><ShieldCheck aria-hidden/><span><strong>Device save is unavailable</strong>{storageError}<details><summary>Show recovery summary</summary><pre>{recoverySummary}</pre></details></span></div>}
  <section className={`drive-glance ${hasBookedReturn?'has-booked-return':''}`} aria-label="Critical ride information"><div><MapPin aria-hidden/><span>Pickup</span><PlaceDisplay request={ride} kind="pickup"/></div><span aria-hidden="true" className="drive-route-connector"/><div><Navigation aria-hidden/><span>Outbound destination</span><PlaceDisplay request={ride} kind="destination"/></div>{hasBookedReturn&&<><span aria-hidden="true" className="drive-route-connector"/><div><Navigation aria-hidden/><span>Booked return stop</span><PlaceDisplay request={ride} kind="return"/></div></>}</section>
  <DriveDirectionsChooser target={navigationTarget} onProviderOpen={rememberNavigationProvider}/>
  <div className="drive-utility-actions">{ride.customerDeleted?<button type="button" className="button secondary" disabled title="This guest’s contact details were removed."><Phone aria-hidden/>Call unavailable</button>:<a className="button secondary" href={`tel:${ride.phone}`}><Phone aria-hidden/>Call {ride.customerName.split(' ')[0]}</a>}<button ref={detailsButton} type="button" className="button secondary" onClick={()=>setDetailsOpen(true)}><Info aria-hidden/>Ride details</button></div>
  <main className="drive-workspace"><section className="drive-stage-card"><div className="drive-stage-heading"><span>Current step</span><strong>{copy.label}</strong><small>{formatDateTime(session.updatedAt)}</small></div>{driveBlockReason&&<p id="drive-action-blocked" className="drive-blocked" role="status"><ShieldCheck aria-hidden/>{driveBlockReason}</p>}{primary&&<button type="button" className="drive-stage-action" onClick={primary.action==='start_heading'?startHeadingToPickup:()=>void advance(primary.action)} disabled={!canOperate||busy} aria-describedby={driveBlockReason?'drive-action-blocked':undefined}>{busy?'Saving…':primary.label}<ChevronRight aria-hidden/></button>}{showAfterDropChoice&&<div className="drive-choice"><p><strong>Where are you heading next?</strong>The booked ride is complete. Only track a base return if you are actually making it.</p><button type="button" className="drive-stage-action" onClick={()=>void advance('return_to_base')} disabled={busy||Boolean(storageError)}>Return to base <ChevronRight aria-hidden/></button><button type="button" className="button secondary" onClick={()=>void advance('continue_elsewhere')} disabled={busy||Boolean(storageError)}>Continue working elsewhere</button></div>}{(session.stage==='completed_elsewhere'||session.stage==='at_base')&&<div className="drive-complete"><CheckCircle2 aria-hidden/><div><strong>Drive session complete</strong><p>{session.stage==='at_base'?'Return to base recorded.':'No return to base was assumed or added.'}</p></div></div>}<ol className={`drive-progress ${hasBookedReturn?'has-return-step':''}`} aria-label="Drive progress"><li className={session.stage!=='ready'?'done':'current'}>Pickup route</li><li className={['passenger_onboard','at_destination','return_passenger_onboard','at_return_stop','returning_to_base','completed_elsewhere','at_base'].includes(session.stage)?'done':session.stage==='at_pickup'?'current':''}>Outbound ride</li>{hasBookedReturn&&<li className={bookedReturnDone?'done':session.stage==='at_destination'||session.stage==='return_passenger_onboard'?'current':''}>Booked return</li>}<li className={showAfterDropChoice||session.stage==='returning_to_base'?'current':['completed_elsewhere','at_base'].includes(session.stage)?'done':''}>After drop-off</li></ol></section>
   <aside className="drive-telemetry"><header><div><span>Actual drive record</span><strong>{actualMiles.toFixed(1)} mi</strong></div>{estimate!==undefined&&<div><span>Route estimate</span><strong>{estimate.toFixed(1)} mi</strong></div>}</header><p className={`tracking-status status-${location.notice.kind}`} aria-live="polite"><LocateFixed aria-hidden/>{location.notice.message}</p><div className="drive-tracking-actions">{location.isWatching?<button type="button" className="button secondary" onClick={()=>location.stop()}><Pause aria-hidden/>Pause GPS mileage</button>:<button type="button" className="button secondary" onClick={location.start} disabled={!canOperate||!['heading_to_pickup','passenger_onboard','return_passenger_onboard','returning_to_base'].includes(session.stage)}><LocateFixed aria-hidden/>{session.trackingConsentAt?'Resume GPS mileage':'Allow & start GPS mileage'}</button>}</div><p className="drive-limit"><strong>Foreground tracking only.</strong> A mobile browser or PWA may pause location when the screen locks or the app is suspended. Keep this page open, or enter mileage manually. No Google route lookup is used for actual miles.</p><details className="manual-mileage-panel"><summary>Enter or correct mileage</summary><ManualMileageEditor session={session} onSave={saveManual}/></details><div className="drive-segments">{(Object.keys(session.segments) as DriveSegmentKind[]).map(kind=><div key={kind}><span>{segmentLabels[kind]}</span><strong>{segmentMiles(session.segments[kind]).toFixed(1)} mi</strong><small>{segmentElapsedMinutes(session.segments[kind])} min{session.segments[kind]?.manualOverride?' · Manual override':''}</small></div>)}{!Object.keys(session.segments).length&&<p className="drive-muted">Segment times and actual mileage appear after the first drive step.</p>}</div><button type="button" className="drive-reset" onClick={resetLocal}><RotateCcw aria-hidden/>Clear device session</button></aside>
  </main>
  {message&&<p className="drive-message" role="status">{message}</p>}{!storageError&&<p className="drive-save-note"><Users aria-hidden/><span><strong>Saved safely on this device</strong>Drive checkpoints, timestamps, and mileage remain device-local until the reviewed owner-only server migration is applied. Request status changes still use the existing protected workflow.</span></p>}{detailsOpen&&<RideDetails request={ride} session={session} onClose={closeDetails}/>}
 </div>;
}
