import { useMemo,useRef,useState } from 'react';
import { Archive,ArrowLeft,ChevronDown,Download,ExternalLink,File,Forward,ImageOff,Inbox,Mail,MailOpen,MailPlus,Paperclip,Reply,ReplyAll,RotateCcw,Save,Search,Send,ShieldCheck,Star,Trash2,X } from 'lucide-react';
import { Link } from 'react-router-dom';
import { StatePanel } from '../components/StatePanel';
import { buildComposeDraft,buildReply,createSendIdempotencyKey,quotedTextParts,validateDraft } from '../features/email-center/domain';
import { emailFeatureState } from '../features/email-center/repository';
import { activateOwnerGmailConnection,beginOwnerGmailOAuth } from '../features/email-center/supabase-provider';
import { attachmentPolicy,formatRecipients,safeLinkDetails,sanitizeEmailHtml,validateAttachmentAccess,validateSendReceipt } from '../features/email-center/security';
import type { ComposeDraft,EmailMessage,EmailThread,MessageAction } from '../features/email-center/types';
import { useOwnerEmail } from '../features/email-center/useOwnerEmail';
import {ownerEmailErrorMessage} from '../features/email-center/error-recovery';
import { formatDateTime } from '../lib/selectors';
import '../features/email-center/email-center.css';

type ComposeState={open:boolean;to:string;cc:string;bcc:string;subject:string;body:string;threadId?:string;inReplyTo?:string;references:string[];draftId?:string;revision?:string;confirmationToken?:string;confirming:boolean;sending:boolean;error:string;notice:string};
const emptyCompose=():ComposeState=>({open:false,to:'',cc:'',bcc:'',subject:'',body:'',references:[],confirming:false,sending:false,error:'',notice:''});

function ThreadRow({thread,active,onOpen}:{thread:EmailThread;active:boolean;onOpen:()=>void}){
  const sender=thread.participants[0];
  return <button type="button" className={`email-thread-row ${active?'is-active':''} ${thread.unread?'is-unread':''}`} onClick={onOpen}>
    <span className="email-thread-signal">{thread.unread?<span aria-label="Unread"/>:null}</span>
    <span className="email-thread-copy"><strong>{sender?.name||sender?.email||'Unknown sender'}</strong><b>{thread.subject||'(no subject)'}</b><small>{thread.snippet||'No preview available.'}</small></span>
    <span className="email-thread-meta"><time>{formatDateTime(thread.lastMessageAt)}</time>{thread.starred?<Star aria-label="Starred"/>:null}{thread.messageCount>1?<em>{thread.messageCount}</em>:null}</span>
  </button>;
}

function MessageBody({message,attachmentsEnabled,provider}:{message:EmailMessage;attachmentsEnabled:boolean;provider:ReturnType<typeof useOwnerEmail>['provider']}){
  const [remoteImages,setRemoteImages]=useState(false),[showQuoted,setShowQuoted]=useState(false),[showAddresses,setShowAddresses]=useState(false),[pendingLink,setPendingLink]=useState<string|null>(null),[attachmentError,setAttachmentError]=useState('');
  const safe=useMemo(()=>sanitizeEmailHtml(message.html||'',message.plainText,{},remoteImages),[message,remoteImages]);
  const text=quotedTextParts(message.plainText);
  const addressesId=`email-addresses-${message.id.replace(/[^A-Za-z0-9_-]/g,'-')}`;
  const frameHeight=Math.min(820,Math.max(380,260+Math.ceil(message.plainText.length/3.6)));
  const openLink=()=>{if(!pendingLink)return;window.open(pendingLink,'_blank','noopener,noreferrer');setPendingLink(null)};
  return <article className={`email-message ${message.direction}`}>
    <header><div className="email-avatar" aria-hidden>{(message.from.name||message.from.email).slice(0,1).toUpperCase()}</div><div><strong>{message.from.name||message.from.email}</strong><button type="button" className="email-address-expander" aria-expanded={showAddresses} aria-controls={addressesId} onClick={()=>setShowAddresses(value=>!value)}>to {formatRecipients(message.to)} <ChevronDown aria-hidden/></button>{showAddresses?<dl id={addressesId} className="email-address-details"><div><dt>From</dt><dd>{formatRecipients([message.from])}</dd></div><div><dt>To</dt><dd>{formatRecipients(message.to)}</dd></div>{message.cc.length?<div><dt>Cc</dt><dd>{formatRecipients(message.cc)}</dd></div>:null}</dl>:null}</div><time>{formatDateTime(message.sentAt)}</time></header>
    {safe.blockedRemoteImages>0&&!remoteImages?<button className="email-image-permission" type="button" onClick={()=>setRemoteImages(true)}><ImageOff aria-hidden/>Load {safe.blockedRemoteImages} remote image{safe.blockedRemoteImages===1?'':'s'} for this message</button>:null}
    {message.html?<div className="email-html-document"><iframe title={`Email content: ${message.subject||'No subject'}`} sandbox="" referrerPolicy="no-referrer" srcDoc={safe.documentHtml} style={{height:`${frameHeight}px`}}/>{safe.links.length?<nav className="email-message-links" aria-label="Links in this message"><span>Links in this email</span>{safe.links.map(link=><button type="button" key={link.href} onClick={()=>setPendingLink(link.href)}><ExternalLink aria-hidden/>{link.domain}</button>)}</nav>:null}</div>:<div className="email-plain-body"><p>{text.visible}</p>{text.quoted?<><button type="button" className="quoted-toggle" onClick={()=>setShowQuoted(value=>!value)}>{showQuoted?'Hide':'Show'} quoted message</button>{showQuoted?<pre>{text.quoted}</pre>:null}</>:null}</div>}
    {message.attachments.length?<section className="email-attachments" aria-label="Attachments">{message.attachments.map(attachment=>{const policy=attachmentPolicy(attachment);return <div key={attachment.id}><File aria-hidden/><span><strong>{attachment.name}</strong><small>{attachment.mimeType} · {(attachment.size/1024).toFixed(0)} KB</small></span><button type="button" disabled={!policy.allowed||!attachmentsEnabled} title={policy.reason||(!attachmentsEnabled?'Authenticated attachment access is not enabled':'Open attachment')} onClick={async()=>{try{setAttachmentError('');const access=await provider.attachmentAccess(message.providerMessageId,attachment.id);window.open(validateAttachmentAccess(access.url,access.expiresAt),'_blank','noopener,noreferrer')}catch(error){setAttachmentError(error instanceof Error?error.message:'Attachment could not be opened.')}}}><Download aria-hidden/>Open</button></div>})}{attachmentError?<p className="compose-error">{attachmentError}</p>:null}</section>:null}
    {pendingLink?<div className="email-link-confirm" role="dialog" aria-modal="true" aria-label="Open external link"><div><ExternalLink aria-hidden/><strong>Open this link?</strong><p>{safeLinkDetails(pendingLink).domain}</p><small>{pendingLink}</small><div><button autoFocus type="button" className="button secondary" onClick={()=>setPendingLink(null)}>Cancel</button><button type="button" className="button primary" onClick={openLink}>Open link</button></div></div></div>:null}
  </article>;
}

function ThreadDetail({thread,messages,currentLabel,onBack,onRespond,onAction,modifyEnabled,attachmentsEnabled,provider}:{thread:EmailThread;messages:EmailMessage[];currentLabel:string;onBack:()=>void;onRespond:(message:EmailMessage,mode:'reply'|'reply_all'|'forward')=>void;onAction:(action:MessageAction)=>Promise<void>;modifyEnabled:boolean;attachmentsEnabled:boolean;provider:ReturnType<typeof useOwnerEmail>['provider']}){
  const latest=messages.at(-1),[actionError,setActionError]=useState(''),[busy,setBusy]=useState(false);
  const inTrash=thread.labels.includes('trash')||currentLabel==='trash';
  const act=async(action:MessageAction)=>{if(action==='trash'&&!window.confirm('Move this conversation to Trash? You can restore it later from the Trash folder.'))return;setBusy(true);setActionError('');try{await onAction(action)}catch(error){setActionError(error instanceof Error?error.message:'Email action could not be verified.')}finally{setBusy(false)}};
  return <section className="email-reading-pane"><header className="email-reading-head"><button type="button" className="email-mobile-back" onClick={onBack}><ArrowLeft aria-hidden/>{currentLabel==='trash'?'Trash':'Inbox'}</button><div><p className="eyebrow">Conversation</p><h2>{thread.subject||'(no subject)'}</h2><span>{thread.messageCount} message{thread.messageCount===1?'':'s'} · {thread.participants.map(item=>item.name||item.email).join(', ')}</span>{actionError?<small className="compose-error">{actionError}</small>:null}</div><div className="email-thread-actions"><button type="button" title={thread.unread?'Mark read':'Mark unread'} disabled={!modifyEnabled||busy} onClick={()=>void act(thread.unread?'mark_read':'mark_unread')}><MailOpen aria-hidden/>{thread.unread?'Read':'Unread'}</button><button type="button" title={thread.starred?'Remove star':'Star'} disabled={!modifyEnabled||busy} onClick={()=>void act(thread.starred?'unstar':'star')}><Star aria-hidden/>{thread.starred?'Unstar':'Star'}</button>{inTrash?<button type="button" title="Restore from Trash" disabled={!modifyEnabled||busy} onClick={()=>void act('untrash')}><RotateCcw aria-hidden/>Restore</button>:<><button type="button" title={currentLabel==='archive'?'Restore to Inbox':'Archive'} disabled={!modifyEnabled||busy} onClick={()=>void act(currentLabel==='archive'?'restore':'archive')}><Archive aria-hidden/>{currentLabel==='archive'?'Restore':'Archive'}</button><button type="button" title="Move to Trash" disabled={!modifyEnabled||busy} onClick={()=>void act('trash')}><Trash2 aria-hidden/>Trash</button></>}</div></header>
    {thread.matchedCustomerId?<aside className="email-customer-link"><ShieldCheck aria-hidden/><span>Matched to a Pxpress guest record</span><Link to={`/customers/${thread.matchedCustomerId}`}>Open guest</Link>{thread.matchedRequestIds[0]?<Link to={`/requests/${thread.matchedRequestIds[0]}`}>Open request</Link>:null}</aside>:null}
    <div className="email-message-stack">{messages.map(message=><MessageBody key={message.id} message={message} attachmentsEnabled={attachmentsEnabled} provider={provider}/>)}</div>
    {latest?<footer className="email-reply-bar"><button type="button" onClick={()=>onRespond(latest,'reply')}><Reply aria-hidden/>Reply</button><button type="button" onClick={()=>onRespond(latest,'reply_all')}><ReplyAll aria-hidden/>Reply all</button><button type="button" onClick={()=>onRespond(latest,'forward')}><Forward aria-hidden/>Forward</button></footer>:null}
  </section>;
}

function ComposeSheet({state,setState,connected,provider}:{state:ComposeState;setState:React.Dispatch<React.SetStateAction<ComposeState>>;connected:boolean;provider:ReturnType<typeof useOwnerEmail>['provider']}){
  const sendLock=useRef(false);
  if(!state.open)return null;
  const prepare=()=>{try{const draft=buildComposeDraft(state);const error=validateDraft(draft);setState(current=>({...current,error,confirming:!error,confirmationToken:error?undefined:crypto.randomUUID()}))}catch(error){setState(current=>({...current,error:error instanceof Error?error.message:'Check the recipients.',confirmationToken:undefined}))}};
  const save=async()=>{try{const draft=buildComposeDraft(state);const saved=await provider.saveDraft(draft,state.revision);setState(current=>({...current,draftId:saved.id,revision:saved.revision,notice:'Draft saved.',error:''}))}catch(error){setState(current=>({...current,error:error instanceof Error?error.message:'Draft could not be saved.'}))}};
  const send=async()=>{if(sendLock.current||state.sending)return;let draft:ComposeDraft;const confirmationToken=state.confirmationToken;if(!confirmationToken){setState(current=>({...current,error:'Review the message again before sending.',confirming:false}));return}sendLock.current=true;setState(current=>({...current,sending:true,error:''}));try{draft=buildComposeDraft(state);const error=validateDraft(draft);if(error){setState(current=>({...current,error,confirming:false,sending:false}));return}const idempotencyKey=createSendIdempotencyKey(draft,confirmationToken);const receipt=await provider.sendDraft(draft,idempotencyKey,confirmationToken);validateSendReceipt(receipt,idempotencyKey);setState(emptyCompose())}catch(error){setState(current=>({...current,confirming:true,sending:false,error:error instanceof Error?error.message:'Message was not sent.'}))}finally{sendLock.current=false}};
  const dirty=Boolean(state.to||state.cc||state.bcc||state.subject||state.body);
  const close=()=>{if(dirty&&!window.confirm('Discard this unsaved message?'))return;setState(emptyCompose())};
  return <div className="compose-overlay" role="dialog" aria-modal="true" aria-label="Compose email"><section className="compose-sheet"><header><div><p className="eyebrow">Owner email</p><h2>{state.threadId?'Reply':'New message'}</h2></div><button type="button" onClick={close} aria-label="Close compose"><X aria-hidden/></button></header><div className="compose-fields"><label><span>To</span><input value={state.to} onChange={event=>setState(current=>({...current,to:event.target.value,error:''}))} autoComplete="off" inputMode="email"/></label><details><summary>Add Cc or Bcc</summary><label><span>Cc</span><input value={state.cc} onChange={event=>setState(current=>({...current,cc:event.target.value}))} inputMode="email"/></label><label><span>Bcc</span><input value={state.bcc} onChange={event=>setState(current=>({...current,bcc:event.target.value}))} inputMode="email"/></label></details><label><span>Subject</span><input value={state.subject} onChange={event=>setState(current=>({...current,subject:event.target.value,error:''}))}/></label><label className="compose-body"><span>Message</span><textarea value={state.body} onChange={event=>setState(current=>({...current,body:event.target.value,error:''}))} placeholder="Write your message"/></label><div className="compose-signature"><strong>Standard Pxpress signature</strong><span>Thank you,<br/>Pxpress<br/>Professional Transportation Services<br/>(234) 200-6969 · pxpressmedia@gmail.com</span></div>{state.error?<p className="compose-error" role="alert">{state.error}</p>:null}{state.notice?<p className="compose-notice">{state.notice}</p>:null}</div><footer><button type="button" className="compose-attachment" disabled title="Uploads stay off until authenticated Gmail attachment handling is verified"><Paperclip aria-hidden/>Attach</button><button type="button" className="button secondary" disabled={!connected||state.sending} onClick={()=>void save()}><Save aria-hidden/>Save draft</button><button type="button" className="button primary" disabled={!connected||state.sending} onClick={prepare}><Send aria-hidden/>Review send</button></footer></section>{state.confirming?<div className="send-confirm" role="alertdialog" aria-modal="true" aria-label="Confirm send"><div><Mail aria-hidden/><p className="eyebrow">Final check</p><h3>Send this email?</h3><dl><div><dt>To</dt><dd>{state.to}</dd></div><div><dt>Subject</dt><dd>{state.subject}</dd></div></dl><p>No message is sent until you confirm here.</p><div><button className="button secondary" type="button" onClick={()=>setState(current=>({...current,confirming:false}))} disabled={state.sending}>Go back</button><button className="button primary" type="button" onClick={()=>void send()} disabled={state.sending}>{state.sending?'Sending…':'Confirm and send'}</button></div></div></div>:null}</div>;
}

export function EmailCenter(){
  const mail=useOwnerEmail(),flags=emailFeatureState();
  const folderName=({inbox:'Inbox',starred:'Starred',sent:'Sent',draft:'Drafts',archive:'Archive',trash:'Trash'} as Record<string,string>)[mail.label]||'Email';
  const [compose,setCompose]=useState<ComposeState>(emptyCompose);
  const [connecting,setConnecting]=useState(false),[activating,setActivating]=useState(false),[connectionError,setConnectionError]=useState('');
  const emailError=connectionError||mail.error;
  const needsMfa=emailError==='OWNER_AAL2_REQUIRED';
  const connectionCheckFailed=Boolean(mail.error)&&!mail.connection.connected;
  const connectGmail=async()=>{if(!flags.connect||connecting)return;setConnecting(true);setConnectionError('');try{const{authorizationUrl}=await beginOwnerGmailOAuth();const target=new URL(authorizationUrl);if(target.protocol!=='https:'||target.hostname!=='accounts.google.com')throw new Error('Google authorization could not be verified.');window.location.assign(target.toString())}catch(error){setConnectionError(error instanceof Error?error.message:'Google connection could not be started.');setConnecting(false)}};
  const activateGmail=async()=>{if(!flags.connect||activating||!window.confirm('Enable Gmail inbox, sending, and message management for the approved Pxpress owner account?'))return;setActivating(true);setConnectionError('');try{await activateOwnerGmailConnection();await mail.load(true,true)}catch(error){setConnectionError(error instanceof Error?error.message:'Gmail could not be enabled.')}finally{setActivating(false)}};
  const openCompose=(message?:EmailMessage,mode?:'reply'|'reply_all'|'forward')=>{if(message&&mode){const reply=buildReply(message,mode);setCompose({...emptyCompose(),open:true,to:reply.to,subject:reply.subject,body:reply.quotedText,threadId:reply.threadId,inReplyTo:reply.inReplyTo,references:reply.references})}else setCompose({...emptyCompose(),open:true})};
  return <div className="page email-center-page"><header className="page-head email-page-head"><div><p className="eyebrow">Owner correspondence</p><h1>Email</h1><p>Raishawn’s private Pxpress inbox, customer conversations, and deliberate sending controls.</p></div><button type="button" className="button primary" onClick={()=>openCompose()} disabled={!flags.compose||!mail.connection.connected||!mail.connection.composeEnabled}><MailPlus aria-hidden/>Compose</button></header>
    {!mail.connection.connected?<aside className="email-disconnected"><div><Mail aria-hidden/><span><strong>{needsMfa?'Verify your identity to connect Gmail':connectionCheckFailed?'Gmail connection could not be checked':mail.connection.status==='paused'?'Gmail is connected and paused':'Gmail is not connected'}</strong><small>{needsMfa?'Use your authenticator to confirm it is really you. You will return here afterward.':connectionCheckFailed?ownerEmailErrorMessage(emailError):mail.connection.status==='paused'?'Enable the approved account to read, send, and manage messages in Owner Desk.':'No inbox, drafts, or messages shown here are simulated. Connect the approved owner account in a controlled setup before using email.'}</small>{connectionError&&!needsMfa?<small className="compose-error" role="alert">{ownerEmailErrorMessage(connectionError)}</small>:null}</span></div>{needsMfa?<Link className="button secondary" to="/mfa-challenge?returnTo=%2Femail&force=1">Verify identity</Link>:connectionCheckFailed?(emailError==='OWNER_AUTHENTICATION_REQUIRED'?<Link className="button secondary" to="/owner-access?returnTo=%2Femail">Sign in again</Link>:<button className="button secondary" type="button" disabled={mail.loading} onClick={()=>void mail.load(true,true)}>Check connection again</button>):mail.connection.status==='paused'?<button className="button secondary" type="button" disabled={!flags.connect||activating} onClick={()=>void activateGmail()}>{activating?'Enabling…':'Enable Gmail'}</button>:<button className="button secondary" type="button" disabled={!flags.connect||connecting} onClick={()=>void connectGmail()}>{flags.connect?(connecting?'Opening Google…':'Connect approved Gmail'):'Connection setup unavailable'}</button>}</aside>:null}
    <section className={`email-workspace ${mail.selected?'has-selection':''}`}>
      <aside className="email-inbox-pane"><div className="email-pane-title"><div><Inbox aria-hidden/><strong>{folderName}</strong>{mail.threads.some(item=>item.unread)?<span>{mail.threads.filter(item=>item.unread).length}</span>:null}</div><small>{mail.connection.accountEmail||'No connected account'}</small></div><div className="email-search"><Search aria-hidden/><input type="search" value={mail.query} onChange={event=>mail.setQuery(event.target.value)} placeholder="Search email" aria-label="Search email"/><select value={mail.label} onChange={event=>mail.setLabel(event.target.value)} aria-label="Filter email"><option value="inbox">Inbox</option><option value="starred">Starred</option><option value="sent">Sent</option><option value="draft">Drafts</option><option value="archive">Archive</option><option value="trash">Trash</option></select></div>
        {mail.loading?<StatePanel kind="loading" title="Checking inbox"/>:mail.error?<StatePanel kind="error" title="Email could not be loaded" body={mail.error} retry={()=>void mail.load(true,true)}/>:mail.threads.length?<div className="email-thread-list">{mail.threads.map(thread=><ThreadRow key={thread.id} thread={thread} active={mail.selected?.thread.id===thread.id} onOpen={()=>void mail.open(thread)}/>)}{mail.nextPageToken?<button className="email-load-more" type="button" onClick={()=>void mail.load(false)}>Load older messages</button>:null}</div>:<StatePanel kind="empty" title={mail.connection.connected?'Inbox is clear':'Connect Gmail to begin'} body={mail.connection.connected?'No messages match this view.':'The email center stays empty until a verified Gmail account is connected.'}/>}</aside>
      {mail.selected?<ThreadDetail thread={mail.selected.thread} messages={mail.selected.messages} currentLabel={mail.label} onBack={()=>mail.setSelected(null)} onRespond={openCompose} onAction={action=>mail.modify(mail.selected!.thread,action)} modifyEnabled={mail.connection.modifyEnabled&&flags.modify} attachmentsEnabled={mail.connection.readEnabled&&flags.attachments} provider={mail.provider}/>:<section className="email-reading-empty"><Mail aria-hidden/><h2>{mail.connection.connected?'Choose a conversation':'Private email, when connected'}</h2><p>{mail.connection.connected?'Open a thread to read the full conversation and safely handle links or documents.':'Read, reply, and manage customer email here after the owner-only Gmail connection passes its security checks.'}</p><ul><li><ShieldCheck aria-hidden/>Remote tracking images blocked by default</li><li><ShieldCheck aria-hidden/>Every send requires final confirmation</li><li><ShieldCheck aria-hidden/>Attachments remain behind authenticated access</li></ul></section>}
    </section>
    <footer className="email-safety-footer"><span><ShieldCheck aria-hidden/>Owner-only · Gmail data never enters browser storage</span><span>Read {flags.read?'enabled':'off'} · Send {flags.compose?'enabled':'off'} · Modify {flags.modify?'enabled':'off'}</span><Link to="/communications">Open lifecycle message history</Link></footer>
    <ComposeSheet state={compose} setState={setCompose} connected={flags.compose&&mail.connection.connected&&mail.connection.composeEnabled} provider={mail.provider}/>
  </div>;
}
