import { BellRing,CheckCircle2,ExternalLink,Info,ShieldCheck } from 'lucide-react';
import { useCallback,useEffect,useState } from 'react';
import { Link } from 'react-router-dom';
import { disableOwnerPushFromTap,enableOwnerPushFromTap,readOwnerPushReadiness,saveOwnerPushPreferences,sendOwnerPushTestFromCurrentDevice,type OwnerPushReadiness } from '../features/owner-notifications/push-repository';
import { getPushCapability,pushFeatureConfigured,type OwnerPushCategory } from '../features/owner-notifications/push-policy';
import { loadNotificationPreferences,saveNotificationPreferences } from '../features/owner-notifications/settings-repository';
const categories:[OwnerPushCategory,string,string][]=[['new_request','New requests','A new customer ride request arrives.'],['payment','Payments','A payment is received, pending, or fails.'],['ride_change','Changes and cancellations','A scheduled ride changes or is cancelled.'],['upcoming','Upcoming rides','Time-sensitive reminders before pickup.'],['tax_review','Tax review','A quote needs rate or filing review.'],['system_error','System issues','A critical delivery or connection fails.']];
const emptyReadiness:OwnerPushReadiness={serverConfigured:false,databaseReady:false,featureEnabled:false,dispatchEnabled:false,subscriptionActive:false,reason:'The secure server channel is not configured.'};
export function NotificationSettings(){
 const [capability,setCapability]=useState(getPushCapability),[readiness,setReadiness]=useState<OwnerPushReadiness>(emptyReadiness),[preferences,setPreferences]=useState(loadNotificationPreferences),[message,setMessage]=useState(''),[pendingDraft,setPendingDraft]=useState<typeof preferences|null>(null),[busy,setBusy]=useState(false),[serverSaved,setServerSaved]=useState(false);
 const refresh=useCallback(async()=>{setCapability(getPushCapability());if(!pushFeatureConfigured()){setReadiness(emptyReadiness);setServerSaved(false);return}try{const state=await readOwnerPushReadiness();setReadiness(state);if(state.preferences){setPreferences(state.preferences);saveNotificationPreferences(state.preferences);setServerSaved(true)}}catch{setReadiness(emptyReadiness);setServerSaved(false)}},[]);
 useEffect(()=>{void refresh()},[refresh]);
 function updateDraft(next:typeof preferences){if(!saveNotificationPreferences(next)){setPendingDraft(next);setServerSaved(false);setMessage('Notification choices could not be saved on this device. Check browser storage and try again.');return}setPreferences(next);setPendingDraft(null);setServerSaved(false);setMessage('Draft saved on this device. It is not active on the server until you choose Save settings.')}
 async function save(){setBusy(true);try{const state=await saveOwnerPushPreferences(preferences);if(!state.preferences)throw new Error('The server did not return saved preferences.');setReadiness(state);setPreferences(state.preferences);const cached=saveNotificationPreferences(state.preferences);setPendingDraft(cached?null:state.preferences);setServerSaved(true);setMessage(cached?'Settings saved and verified on the secure server.':'Settings were saved on the secure server, but this device could not cache them.')}catch(error){setServerSaved(false);setMessage(error instanceof Error?error.message:'Settings could not be saved.')}finally{setBusy(false);setCapability(getPushCapability())}}
 async function enable(){setBusy(true);try{const result=await enableOwnerPushFromTap(import.meta.env.VITE_PXPRESS_WEB_PUSH_PUBLIC_KEY||'',readiness,navigator.userAgent.slice(0,100));setReadiness(result.readiness);setMessage(result.permission==='granted'?'This device is subscribed.':'Device permission was not granted.')}catch(error){setMessage(error instanceof Error?error.message:'Phone notifications could not be enabled.')}finally{setBusy(false);await refresh()}}
 async function disable(){setBusy(true);try{setReadiness(await disableOwnerPushFromTap());setMessage('This device was removed from phone notifications.')}catch(error){setMessage(error instanceof Error?error.message:'This device could not be removed.')}finally{setBusy(false);await refresh()}}
 async function sendTest(){setBusy(true);try{await sendOwnerPushTestFromCurrentDevice();setMessage('A one-time test was queued for this device. It is not a confirmation until it appears on this phone.')}catch(error){setMessage(error instanceof Error?error.message:'The device test could not be queued.')}finally{setBusy(false);await refresh()}}
 const backendReady=pushFeatureConfigured()&&readiness.serverConfigured&&readiness.databaseReady&&readiness.featureEnabled,status=!capability.supported?'Not supported':!capability.installed?'Add to Home Screen first':!backendReady?'Not configured':readiness.subscriptionActive?'Enabled on this device':capability.permission==='denied'?'Blocked in device settings':'Ready to enable';
 return <div className="page notification-settings-page"><header className="page-head"><div><p className="eyebrow">Notification settings</p><h1>Stay ahead of every ride.</h1><p>In-app alerts remain available independently. Phone push stays off until the secure server channel is configured and Raishawn enables this device.</p></div><Link className="button secondary" to="/notifications">Back to notifications</Link></header>
 <section className="notification-settings-card notification-device-card"><div className="notification-settings-icon"><BellRing aria-hidden/></div><div><p className="eyebrow">This device</p><h2>{status}</h2><p>{capability.reason||readiness.reason||'Permission is requested only after you tap Enable.'}</p></div>{readiness.subscriptionActive?<button type="button" className="button secondary" onClick={disable} disabled={busy}>Disable on this device</button>:<button type="button" className="button primary" onClick={enable} disabled={busy||!backendReady||!capability.supported||!capability.installed||capability.permission==='denied'}>Enable device notifications</button>}</section>{message&&<p className={`notification-settings-message ${pendingDraft?'is-error':''}`} role={pendingDraft?'alert':'status'}><span>{message}</span>{pendingDraft?<button type="button" onClick={()=>updateDraft(pendingDraft)}>Try saving again</button>:null}</p>}
 <div className="notification-settings-grid"><section className="notification-settings-card"><header><p className="eyebrow">Alert categories</p><h2>Choose what reaches this phone</h2></header><div className="notification-toggle-list">{categories.map(([key,label,detail])=><label key={key}><span><strong>{label}</strong><small>{detail}</small></span><input type="checkbox" checked={preferences.categories[key]} onChange={event=>updateDraft({...preferences,categories:{...preferences.categories,[key]:event.target.checked}})}/></label>)}</div></section>
 <section className="notification-settings-card"><header><p className="eyebrow">Delivery</p><h2>Quiet hours</h2></header><label className="quiet-toggle"><span><strong>Use quiet hours</strong><small>Critical payment and system email cannot be disabled here.</small></span><input type="checkbox" checked={preferences.quietHours.enabled} onChange={event=>updateDraft({...preferences,quietHours:{...preferences.quietHours,enabled:event.target.checked}})}/></label><div className="quiet-time-grid"><label>From<input type="time" value={preferences.quietHours.start} onChange={event=>updateDraft({...preferences,quietHours:{...preferences.quietHours,start:event.target.value}})}/></label><label>Until<input type="time" value={preferences.quietHours.end} onChange={event=>updateDraft({...preferences,quietHours:{...preferences.quietHours,end:event.target.value}})}/></label></div><label className="quiet-toggle"><span><strong>Phone push</strong><small>In-app alerts stay on. Critical email remains on.</small></span><input type="checkbox" checked={preferences.channels.push} onChange={event=>updateDraft({...preferences,channels:{...preferences.channels,push:event.target.checked}})}/></label><button type="button" className="button primary" onClick={save} disabled={busy||!backendReady}>{serverSaved?'Saved on server':'Save settings'}</button><div className="channel-policy"><ShieldCheck aria-hidden/><p><strong>Default channel policy</strong> Routine work uses in-app and push. Payment, security, and failed-delivery escalation retain email.</p></div></section></div>
 <section className="notification-install-note"><Info aria-hidden/><div><strong>Using an iPhone or iPad?</strong><p>Open Owner Desk in Safari, tap Share, then Add to Home Screen. Open that installed icon and return here.</p></div><ExternalLink aria-hidden/></section><button type="button" className="button secondary notification-test-button" onClick={sendTest} disabled={busy||!backendReady||!readiness.dispatchEnabled||!readiness.subscriptionActive} title="Requires AAL2 and uses only this browser's active subscription"><CheckCircle2 aria-hidden/> Send a test notification</button></div>;
}
