import { CalendarDays,Check,CheckCircle2,CreditCard,Mail,MapPin,Phone,Save,Users,X } from 'lucide-react';
import { useEffect,useRef,useState } from 'react';
import {useOptionalAuth} from '../auth';
import {QuoteReleaseResult} from '../components/QuoteReleaseResult';
import {canReviewExpiredQuote,pendingRelease,releaseTarget,type QuoteReleaseResult as QuoteReleaseValue} from '../lib/quote-release-result';
import { Link,useParams } from 'react-router-dom';
import { DeclineDialog } from '../components/DeclineDialog';
import { CompleteRideDialog } from '../components/CompleteRideDialog';
import { LifecyclePanel } from '../components/LifecyclePanel';
import { OWNER_PAYMENT_CANARY_RIDE_ID,PriceDecisionDialog } from '../components/PriceDecisionDialog';
import { QuoteReleaseDialog } from '../components/QuoteReleaseDialog';
import { RequestProgress } from '../components/RequestProgress';
import { serviceLabels } from '../components/RequestTable';
import { StatePanel } from '../components/StatePanel';
import '../owner-quick-actions.css';
import { useEvents,useRequests } from '../hooks';
import { addInternalNote,approveAndPreparePayment,calculateRouteEstimate,completePaidRide,declineRequest,readManualQuoteRelease,releaseManualQuoteForPayment,requestWixProviderReconciliation,resetExactPaymentCanaryForTaxRequote,verifyWixPayLinkPayment } from '../lib/repository';
import { allowedTransitions,approvalStatuses,formatDate,formatDateTime,formatMoney,formatTime } from '../lib/selectors';
import type { FollowUpPresentation,LifecycleEffect,RideRequest,RouteEstimate,WixReconciliationAction,WixReconciliationIdentity } from '../types';
import type { OwnerPriceDecision } from '../features/fare-recommendation/domain';
import { ManualMileageEditor, routePlanForRequest } from '../features/route-estimate/ManualMileageEditor';
import { readRouteEstimateSession, writeRouteEstimateSession } from '../features/route-estimate/session-cache';
import { NavigationLauncher } from '../features/navigation/NavigationLauncher';
import { GuestMessageJourney } from '../components/GuestMessageJourney';
import { PlaceDisplay } from '../features/places/PlaceDisplay';
type Props={request:RideRequest;reload:()=>void;events:ReturnType<typeof useEvents>};

export function RequestPriceSummary({request}:{request:RideRequest}){
  const draft=request.manualQuoteDraft;
  const amount=draft?draft.customerTotalMinor/100:request.quoteAmount;
  const label=draft?(!draft.isCurrent?'Saved quote · needs review':draft.status==='approved'?'Approved quote':'Quote draft'):'Ride price';
  return <div className="request-price-summary" aria-label="Ride price summary"><span>{label}</span><strong>{formatMoney(amount)}</strong></div>;
}

function DetailContent({request,reload,events}:Props){
  const [notes,setNotes]=useState(''),[saving,setSaving]=useState(false),[message,setMessage]=useState(''),[priceOpen,setPriceOpen]=useState(false),[quoteReviewOpen,setQuoteReviewOpen]=useState(false),[declineOpen,setDeclineOpen]=useState(false),[completeOpen,setCompleteOpen]=useState(false),[canaryResetReason,setCanaryResetReason]=useState(''),[estimate,setEstimate]=useState<RouteEstimate|null>(()=>readRouteEstimateSession(request)),[routeBusy,setRouteBusy]=useState(false),[routeMessage,setRouteMessage]=useState('');
  const [releaseAttempted,setReleaseAttempted]=useState(false),[releaseResult,setReleaseResult]=useState<QuoteReleaseValue|null>(null);
  const releaseLock=useRef(false);
  const ownerId=useOptionalAuth()?.user?.id;
  useEffect(()=>{releaseLock.current=false;setReleaseAttempted(false);setReleaseResult(null);setQuoteReviewOpen(false)},[request.id,request.manualQuoteDraft?.quoteId,ownerId]);
  const canApprove=approvalStatuses.has(request.status),canDecline=(allowedTransitions[request.status]||[]).includes('declined'),canComplete=request.paymentStatus==='paid'&&new Set(['confirmed','in_progress']).has(request.status);
  const canReviewExpired=canReviewExpiredQuote(releaseResult,request,ownerId);
  const destination=request.destinationAddress||request.airport||'',returnTime=request.returnTime;
  const routePlan=routePlanForRequest(request);
  useEffect(()=>{setEstimate(readRouteEstimateSession(request));setRouteBusy(false);setRouteMessage('')},[request.id,request.pickupAddress,request.destinationAddress,request.returnAddress,request.airport,request.tripType]);

  async function approve(decision:OwnerPriceDecision){setSaving(true);setMessage('');try{await approveAndPreparePayment(request,decision);setMessage(`Draft saved at USD ${(decision.customerTotalMinor/100).toFixed(2)}: service ${(decision.serviceSubtotalMinor/100).toFixed(2)}${decision.salesTaxMinor?` + included tax ${(decision.salesTaxMinor/100).toFixed(2)}`:''}. Customer has not been emailed.`);setPriceOpen(false);reload();events.reload()}catch(error){setMessage(error instanceof Error?error.message:'Unable to save the quote draft.');throw error}finally{setSaving(false)}}
  async function releaseQuote(){
    if(releaseLock.current)return;
    releaseLock.current=true;setReleaseAttempted(true);setSaving(true);setMessage('');
    const target=releaseTarget(request,ownerId);if(target)setReleaseResult(pendingRelease(target));
    try{
      const result=await releaseManualQuoteForPayment(request,ownerId);
      setReleaseResult(result);setQuoteReviewOpen(false);reload();events.reload();
    }finally{setSaving(false)}
  }
  async function checkQuote(){if(saving)return;setSaving(true);try{const result=await readManualQuoteRelease(request,ownerId);setReleaseResult(result);if(canReviewExpiredQuote(result,request,ownerId)){releaseLock.current=false;setReleaseAttempted(false)}}finally{setSaving(false)}}
  async function decline(reason:string){setSaving(true);setMessage('');try{await declineRequest(request,reason);setMessage('Request declined.');setDeclineOpen(false);reload();events.reload()}catch(error){setMessage(error instanceof Error?error.message:'Unable to decline the request.');throw error}finally{setSaving(false)}}
  async function saveNote(){if(!notes.trim())return;setSaving(true);try{await addInternalNote(request.id,request.version||1,notes.trim());setNotes('');setMessage('Owner note saved.');reload();events.reload()}catch(error){setMessage(error instanceof Error?error.message:'Unable to save note.')}finally{setSaving(false)}}
  async function mileage(){if(routeBusy||routePlan.error)return;setRouteBusy(true);setRouteMessage('');try{const value=await calculateRouteEstimate(request.id,JSON.stringify(routePlan.stops));setEstimate(value);writeRouteEstimateSession(request,value);setRouteMessage(value.cacheStatus==='cache'?'Recent Google mileage reused. This route did not use another lookup.':'Google mileage calculated. It will be reused in this open tab without another lookup.')}catch(error){setRouteMessage(error instanceof Error?error.message:'Mileage could not be calculated. Use manual mileage below.')}finally{setRouteBusy(false)}}
  function useManualMileage(value:RouteEstimate){setEstimate(value);writeRouteEstimateSession(request,value);setRouteMessage('Manual mileage is ready for pricing in this tab session. No Google lookup was used.')}
  async function reconcile(effect:LifecycleEffect,action:WixReconciliationAction,reason:string,identity:WixReconciliationIdentity){await requestWixProviderReconciliation(effect,action,reason,identity);setMessage('Authoritative reconciliation was requested. No provider state changed from this screen.');reload();events.reload()}
  async function verifyPayment(reason:string){setMessage('');await verifyWixPayLinkPayment(request,reason);setMessage('Wix payment was verified. Refreshing the request now.');reload();events.reload()}
  async function completeRide(presentation:FollowUpPresentation){setSaving(true);setMessage('');try{const result=await completePaidRide(request,presentation);setCompleteOpen(false);setMessage(`Ride completed. The ${result.presentation} thank-you was prepared once. Check Customer emails below for its delivery status.`);reload();events.reload()}catch(error){setMessage(error instanceof Error?error.message:'Unable to complete this ride.');throw error}finally{setSaving(false)}}
  async function resetCanary(){setSaving(true);setMessage('');try{await resetExactPaymentCanaryForTaxRequote(request,canaryResetReason);setCanaryResetReason('');setMessage('Legacy canary moved to payment failed. No payment link was created or sent. Re-open pricing only after exact-address Finder review.');reload();events.reload()}catch(error){setMessage(error instanceof Error?error.message:'Canary could not be reset.')}finally{setSaving(false)}}

  return <div className="page detail-page">
    <nav className="request-destination-nav" aria-label="Ride navigation"><Link to="/requests" replace>All rides</Link></nav>
    <RequestPriceSummary request={request}/>
    {request.manualQuoteDraft?.isCurrent&&<button type="button" className="button secondary" disabled={saving} onClick={checkQuote}>Check quote status</button>}
    {releaseResult&&<QuoteReleaseResult key={JSON.stringify([request.id,request.version,request.manualQuoteDraft?.quoteId,request.customerId,request.email,ownerId])} result={releaseResult} request={request} ownerId={ownerId}/>}
    <header className="detail-head detail-trip-head"><div><div className="detail-title-row"><div><p className="eyebrow">{request.requestNumber}</p><h1>{request.customerName}</h1></div><p className="detail-received"><span>Received</span><time dateTime={request.createdAt}>{formatDateTime(request.createdAt)}</time></p></div><dl className="detail-trip-facts"><div><dt>Service</dt><dd>{serviceLabels[request.service]}</dd></div><div><dt>Date</dt><dd>{formatDate(request.pickupDate)}</dd></div><div><dt>Pickup time</dt><dd>{request.pickupTime?formatTime(request.pickupTime):'Not provided'}</dd></div></dl></div></header>
    <div className="detail-flow">
      <section className="detail-card route-card"><div className="card-title"><MapPin aria-hidden/><div><p className="eyebrow">Ride details</p><h2>{request.tripType}</h2></div></div><div className="route"><div className="route-stops"><div><span>Pickup</span><PlaceDisplay request={request} kind="pickup"/></div><div><span>{request.service==='hourly'?'Final destination':'Drop-off'}</span><PlaceDisplay request={request} kind="destination"/></div>{request.returnAddress&&<div><span>Return{returnTime?` · ${formatTime(request.returnTime)}`:''}</span><PlaceDisplay request={request} kind="return"/></div>}</div>{request.service==='hourly'&&<section className="hourly-reservation"><span>Reserved time</span><strong>{request.pickupTime?formatTime(request.pickupTime):'Start to confirm'} · {request.hourlyEnd?`until ${formatTime(request.hourlyEnd)}`:'end to confirm'}</strong></section>}</div><NavigationLauncher request={request}/><div className="route-actions route-utility-actions"><Link className="button secondary" to="/calendar"><CalendarDays aria-hidden/> Calendar</Link></div><div className="mileage-panel"><div><p className="eyebrow">Mileage</p>{estimate?<><strong>{estimate.totalMiles.toFixed(1)} miles</strong>{estimate.routeLegs?.length?<ol className="route-mileage-legs">{estimate.routeLegs.map((leg,index)=><li key={`${leg.origin}:${leg.destination}`}><span>{routePlan.labels[index]||`Leg ${index+1}`}</span><b>{leg.miles.toFixed(1)} mi · {leg.durationMinutes} min</b></li>)}</ol>:<span>{estimate.baseToPickupMiles.toFixed(1)} base → pickup · {estimate.pickupToDestinationMiles.toFixed(1)} ride · {estimate.destinationToBaseMiles.toFixed(1)} return</span>}<small>{estimate.totalDurationMinutes} estimated driving minutes · {estimate.sourceAttribution} · {estimate.cacheStatus==='cache'?'saved result, no new lookup':estimate.sourceAttribution==='Owner entered'?'entered manually':`calculated ${formatDateTime(estimate.calculatedAt)}`}</small></>:<><strong>Not calculated</strong><span>{routePlan.labels.join(' · ')||'Route details incomplete'}</span></>}</div><button className="button secondary" onClick={mileage} disabled={routeBusy||estimate?.sourceAttribution==='Google Maps'||Boolean(routePlan.error)} title={routePlan.error}>{routeBusy?'Calculating…':estimate?.sourceAttribution==='Google Maps'?'Google mileage ready':'Calculate mileage'}</button></div>{routeMessage&&<p className="guard-note" role="status">{routeMessage}</p>}<ManualMileageEditor request={request} onSave={useManualMileage}/></section>

      <section id="decision" className="control-card decision-card"><div><p className="eyebrow">Request decision</p><h2>{canComplete?'Ready to finish the ride.':canApprove?'Choose what to do with this request.':'No decision waiting.'}</h2></div><div className="decision-actions">{canComplete&&<button type="button" className="button primary decision-primary" onClick={()=>setCompleteOpen(true)}><CheckCircle2 aria-hidden/>Complete Ride</button>}{(canApprove||canReviewExpired)&&<button type="button" className="button primary decision-primary" disabled={saving||releaseAttempted} onClick={()=>request.manualQuoteDraft?.isCurrent?setQuoteReviewOpen(true):setPriceOpen(true)}><Check aria-hidden/>{canReviewExpired?'Review saved quote':request.manualQuoteDraft?.isCurrent?'Review quote':'Set quote'}</button>}{canDecline&&<button type="button" className="button decline-quiet" onClick={()=>setDeclineOpen(true)}><X aria-hidden/>Decline request</button>}</div>{request.id===OWNER_PAYMENT_CANARY_RIDE_ID&&request.status==='deposit_pending'&&<div className="canary-reset-control"><strong>Legacy payment-test recovery</strong><p>Owner MFA and a recorded reason are required. This remains blocked if a provider payment or live link needs reconciliation.</p><label><span>Reset reason</span><textarea rows={2} value={canaryResetReason} onChange={event=>setCanaryResetReason(event.target.value)} placeholder="Why this legacy canary needs a fresh tax-safe quote"/></label><button type="button" className="button secondary" disabled={saving||canaryResetReason.trim().length<8} onClick={resetCanary}>Reset for tax-safe re-quote</button></div>}{!canComplete&&!canApprove&&!canDecline&&request.id!==OWNER_PAYMENT_CANARY_RIDE_ID&&<p className="control-help">This request has moved beyond the owner decision step. Check its progress below.</p>}{message&&<p className="save-message" role="status">{message}</p>}</section>

      <section className="detail-card guest-card"><div className="card-title"><Users aria-hidden/><div><p className="eyebrow">Guest</p><h2>{request.customerName}</h2></div></div><p className="guest-count">{request.passengers} passenger{request.passengers===1?'':'s'}</p>{request.customerDeleted?<p className="muted">Contact details were removed.</p>:<div className="contact-actions"><a className="button secondary" href={`tel:${request.phone}`}><Phone aria-hidden/> Call</a><a className="button secondary" href={`mailto:${request.email}`}><Mail aria-hidden/> Email</a></div>}<dl className="facts"><div><dt>Email</dt><dd>{request.customerDeleted?'Removed':request.email}</dd></div><div><dt>Phone</dt><dd>{request.customerDeleted?'Removed':request.phone}</dd></div></dl>{request.customerNotes&&<blockquote>{request.customerNotes}</blockquote>}</section>

       <section className="detail-card quote-card"><div className="card-title"><CreditCard aria-hidden/><div><p className="eyebrow">Price</p><h2>{request.manualQuoteDraft?formatMoney(request.manualQuoteDraft.customerTotalMinor/100):formatMoney(request.quoteAmount)}</h2></div></div>{request.manualQuoteDraft?<section className="manual-quote-draft"><p className="eyebrow">{request.manualQuoteDraft.isCurrent?(request.manualQuoteDraft.status==='approved'?'Approved quote':'Quote draft'):'Draft needs refresh'}</p><dl className="facts">{request.manualQuoteDraft.inputSemantics==='final_customer_total_tax_included'?<div><dt>Final customer price</dt><dd>{formatMoney(request.manualQuoteDraft.enteredCustomerTotalMinor!/100)}</dd></div>:<div><dt>Historic base fare</dt><dd>{formatMoney(request.manualQuoteDraft.enteredBaseFareMinor!/100)}</dd></div>}<div><dt>Tax rate</dt><dd>{(request.manualQuoteDraft.rateBasisPoints/100).toFixed(2)}%</dd></div><div><dt>Sales tax</dt><dd>{formatMoney(request.manualQuoteDraft.salesTaxMinor/100)}</dd></div><div><dt>Customer total</dt><dd>{formatMoney(request.manualQuoteDraft.customerTotalMinor/100)}</dd></div></dl><p className="payment-note"><strong>Saved quote — email delivery unconfirmed.</strong> Review this quote before anything is released. This desk never collects raw card data.</p></section>:<p className="payment-note">Set a quote when you are ready. Email delivery is unconfirmed. This desk never collects raw card data.</p>}<RequestProgress request={request}/></section>

      <section className="control-card notes-card"><div><p className="eyebrow">Owner notes</p><h2>Keep the ride context together.</h2></div>{request.ownerNoteHistory?.length?<ol className="owner-note-history" aria-label="Owner notes, oldest first">{request.ownerNoteHistory.map((entry,index)=><li key={entry.createdAt+':'+index}><time dateTime={entry.createdAt}>{formatDateTime(entry.createdAt)} Eastern</time><p>{entry.note}</p></li>)}</ol>:request.ownerNotes&&<div className="existing-note"><span>Existing note</span><p>{request.ownerNotes}</p></div>}<label>Add a note<span className="note-help">Adds to the record; existing notes stay unchanged.</span><textarea value={notes} onChange={event=>setNotes(event.target.value)} rows={4}/></label><button type="button" className="button secondary full" onClick={saveNote} disabled={saving||!notes.trim()} title={!notes.trim()?'Write a note before saving.':undefined}><Save aria-hidden/>{saving?'Saving…':'Add note'}</button></section>

      <details className="secondary-operations"><summary>Record details and delivery status</summary><GuestMessageJourney request={request}/><LifecyclePanel request={request} onReconcile={reconcile} onVerifyPayment={verifyPayment}/><section className="timeline-card audit-card"><p className="eyebrow">Activity</p><h2>Request history</h2>{events.loading?<StatePanel kind="loading" title="Loading request history"/>:events.error?<StatePanel kind="error" title="History could not be loaded" body={events.error} retry={events.reload}/>:events.data.length?<ol className="timeline">{events.data.map(event=><li key={event.id}><CheckCircle2 aria-hidden/><div><strong>{event.action}</strong><span>{event.actor} · {formatDateTime(event.at)}</span><p>{event.detail}</p></div></li>)}</ol>:<StatePanel kind="empty" title="No recorded activity yet"/>}</section></details>
    </div>
    {priceOpen&&<PriceDecisionDialog request={request} busy={saving} onDismiss={()=>setPriceOpen(false)} onConfirm={approve}/>} {quoteReviewOpen&&<QuoteReleaseDialog request={request} recovery={canReviewExpired} busy={saving} onDismiss={()=>setQuoteReviewOpen(false)} onEdit={()=>{setQuoteReviewOpen(false);setPriceOpen(true)}} onRelease={releaseQuote}/>} {declineOpen&&<DeclineDialog request={request} busy={saving} onDismiss={()=>setDeclineOpen(false)} onConfirm={decline}/>} {completeOpen&&<CompleteRideDialog request={request} busy={saving} onDismiss={()=>setCompleteOpen(false)} onConfirm={completeRide}/>}
  </div>;
}

export function RequestDetail(){const {id}=useParams(),requests=useRequests(),events=useEvents(id);const request=requests.data.find(item=>item.id===id);if(requests.loading&&!request)return <StatePanel kind="loading" title="Opening request"/>;if(requests.error&&!request)return <StatePanel kind="error" title="Request could not be loaded" body={requests.error} retry={requests.reload}/>;if(!request)return <div className="page detail-page"><nav className="request-destination-nav" aria-label="Ride navigation"><Link to="/requests" replace>All rides</Link></nav><StatePanel kind="empty" title="Request not found" body="This request may have been removed or the link may be outdated."/></div>;return <><DetailContent key={request.id} request={request} reload={requests.reload} events={events}/>{requests.error&&<StatePanel kind="error" title="Latest request update unavailable" body={requests.error} retry={requests.reload}/>}</>}
