import {render,screen,fireEvent,waitFor} from '@testing-library/react';
import {describe,it,expect,vi,beforeEach} from 'vitest';
const api=vi.hoisted(()=>({read:vi.fn(),save:vi.fn(),prepare:vi.fn()}));
vi.mock('./public-finder-repository',()=>({readPublicFinderState:api.read,savePublicFinderPrice:api.save,preparePublicFinderContext:api.prepare}));
import {PublicFinderPricePanel} from './PublicFinderPricePanel';
const state={connected:true,dispatchEnabled:false,consumerEnabled:false,policies:[],job:{id:'job',requestRevision:1,status:'held_policy',pricingReady:false},paymentDeliveryAllowed:false};
beforeEach(()=>vi.resetAllMocks());
describe('public Finder owner bridge',()=>{
 it('holds without approved policy and does not manufacture a date or rate',async()=>{api.read.mockResolvedValue(state);render(<PublicFinderPricePanel requestId="ride" pickupAddress="1 Test St" subtotalMinor={10000}/>);expect(await screen.findByText(/policy must be approved/)).toBeInTheDocument();expect(screen.getByRole('button',{name:'Save reviewed price draft',hidden:true})).toBeDisabled();expect(api.save).not.toHaveBeenCalled();});
 it('saves a current price draft then requires persisted current readback',async()=>{api.read.mockResolvedValueOnce({...state,job:{...state.job,status:'accepted',pricingReady:true}}).mockResolvedValueOnce({...state,draft:{id:'draft',serviceSubtotalMinor:10185,taxMinor:815,totalMinor:11000,current:true}});api.save.mockResolvedValue({id:'draft'});render(<PublicFinderPricePanel requestId="ride" pickupAddress="1 Test St" subtotalMinor={10000}/>);const button=await screen.findByRole('button',{name:'Save reviewed price draft',hidden:true});await waitFor(()=>expect(button).toBeEnabled());fireEvent.click(button);expect(await screen.findByText(/Price draft saved/)).toBeInTheDocument();expect(api.save).toHaveBeenCalledWith('job',10000);expect(screen.getByText(/service \$101.85/)).toBeInTheDocument();});
 it('rejects a stale saved draft instead of presenting success',async()=>{api.read.mockResolvedValueOnce({...state,job:{...state.job,pricingReady:true}}).mockResolvedValueOnce({...state,draft:{id:'draft',serviceSubtotalMinor:10185,taxMinor:815,totalMinor:11000,current:false}});api.save.mockResolvedValue({id:'draft'});render(<PublicFinderPricePanel requestId="ride" pickupAddress="1 Test St" subtotalMinor={10000}/>);fireEvent.click(await screen.findByRole('button',{name:'Save reviewed price draft',hidden:true}));expect(await screen.findByText(/no longer current/)).toBeInTheDocument();expect(screen.queryByText(/Price draft saved/)).not.toBeInTheDocument();});
 it('shows the exact matched address, effective date, rate, and official evidence link',async()=>{api.read.mockResolvedValue({...state,job:{...state.job,status:'accepted',pricingReady:true,evidence:{matchedAddress:'1 CAPITOL SQ, COLUMBUS, OH 43215',applicableDate:'2026-09-07',observedAt:'2026-09-07T16:09:34.503Z',sourceUrl:'https://thefinder.tax.ohio.gov/StreamlineSalesTaxWeb/default.aspx',jurisdiction:'Franklin (25) with COTA',rateBasisPoints:800}}});render(<PublicFinderPricePanel requestId="ride" pickupAddress="1 Test St" subtotalMinor={10000}/>);expect(await screen.findByText('1 CAPITOL SQ, COLUMBUS, OH 43215')).toBeInTheDocument();expect(screen.getByText('2026-09-07')).toBeInTheDocument();expect(screen.getByText(/Franklin \(25\) with COTA · 8.00%/)).toBeInTheDocument();expect(screen.getByRole('link',{name:'Open Ohio Finder source'})).toHaveAttribute('href','https://thefinder.tax.ohio.gov/StreamlineSalesTaxWeb/default.aspx');});
});
