import '@fontsource/dm-sans/400.css';
import '@fontsource/dm-sans/500.css';
import '@fontsource/dm-sans/600.css';
import React from 'react';
import ReactDOM from 'react-dom/client';
import { BrowserRouter } from 'react-router-dom';
import { AuthProvider } from './auth';
import { App } from './App';
import './styles.css';
import './lifecycle.css';
import './wix-payment-recovery.css';
import './calendar-state.css';
import './analytics.css';
import './directory.css';
import './calendar.css';
import './touch-targets.css';
import './owner-operations.css';
import './features/owner-notifications/owner-notifications.css';
import './session-feedback.css';
import './motion.css';
import './owner-desk.css';
import './owner-refinement.css';
import './touch-workspace.css';
import './today-workspace.css';
import './owner-theme.css';
import { registerOwnerServiceWorker } from './features/owner-notifications/register-service-worker';
registerOwnerServiceWorker();
ReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode><BrowserRouter basename="/admin"><AuthProvider><App/></AuthProvider></BrowserRouter></React.StrictMode>);
