import { describe,expect,it } from 'vitest';
import { buildComposeDraft,buildReply,createSendIdempotencyKey,dedupeThreads,matchCustomerByEmail,PXPRESS_SIGNATURE,quotedTextParts,validateDraft } from './domain';
import type { EmailMessage,EmailThread } from './types';

const message:EmailMessage={id:'m1',threadId:'t1',providerMessageId:'pm1',rfcMessageId:'<m1@example.com>',references:['<root@example.com>'],from:{name:'Guest',email:'guest@example.com'},to:[{email:'pxpressmedia@gmail.com'}],cc:[{email:'helper@example.com'}],subject:'Ride request',sentAt:'2026-09-02T18:30:00Z',direction:'received',plainText:'Hello\n> Old quote',unread:true,attachments:[]};
describe('email compose and threading',()=>{
  it('adds the exact standardized Pxpress signature',()=>{const draft=buildComposeDraft({to:'guest@example.com',subject:'Update',body:'Your ride is ready.'});expect(draft.plainText).toBe(`Your ride is ready.${PXPRESS_SIGNATURE}`);expect(validateDraft(draft)).toBe('')});
  it('requires recipient, subject, and body',()=>{expect(validateDraft(buildComposeDraft({subject:'Test',body:'Body'}))).toMatch(/recipient/);expect(validateDraft(buildComposeDraft({to:'a@b.com',body:'Body'}))).toMatch(/subject/);expect(validateDraft(buildComposeDraft({to:'a@b.com',subject:'Test'}))).toMatch(/message/)});
  it('preserves reply identity and References',()=>{const reply=buildReply(message,'reply');expect(reply).toMatchObject({threadId:'t1',inReplyTo:'<m1@example.com>',subject:'Re: Ride request'});expect(reply.references).toEqual(['<root@example.com>','<m1@example.com>'])});
  it('places the signature before quoted history and rejects a reply with no new text',()=>{const reply=buildReply(message,'reply');const draft=buildComposeDraft({...reply,body:`Thanks.${reply.quotedText}`});expect(draft.plainText.indexOf('Pxpress')).toBeLessThan(draft.plainText.indexOf('On 2026'));expect(validateDraft(buildComposeDraft({...reply,body:reply.quotedText}))).toMatch(/message/)});
  it('reply all deduplicates exact normalized participants',()=>{const reply=buildReply({...message,to:[{email:'GUEST@example.com'},{email:'owner@example.com'}]},'reply_all');expect(reply.to).toBe('Guest <guest@example.com>, owner@example.com')});
  it('forward starts a new thread',()=>{expect(buildReply(message,'forward')).toMatchObject({subject:'Fwd: Ride request',to:'',threadId:undefined,inReplyTo:undefined})});
  it('collapses quoted text',()=>{expect(quotedTextParts(message.plainText)).toEqual({visible:'Hello',quoted:'> Old quote'})});
  it('deduplicates paginated threads by provider identity',()=>{const base:EmailThread={id:'1',providerThreadId:'provider-t1',historyId:'1',subject:'A',participants:[],snippet:'old',lastMessageAt:'2026-09-01T10:00:00Z',unread:false,starred:false,labels:['inbox'],messageCount:1,matchedRequestIds:[]};expect(dedupeThreads([base,{...base,id:'2',historyId:'2',snippet:'new',lastMessageAt:'2026-09-02T10:00:00Z'}])).toMatchObject([{id:'2',snippet:'new'}])});
  it('matches a guest only by exact normalized email',()=>{expect(matchCustomerByEmail([{email:'GUEST@example.com'}],[{id:'c1',email:'guest@example.com'}])).toBe('c1');expect(matchCustomerByEmail([{email:'other@example.com'}],[{id:'c1',email:'guest@example.com'}])).toBeUndefined()});
  it('creates stable send keys while nonce separates intentional sends',()=>{const draft=buildComposeDraft({to:'guest@example.com',subject:'A',body:'B'});expect(createSendIdempotencyKey(draft,'nonce-one')).toBe(createSendIdempotencyKey(draft,'nonce-one'));expect(createSendIdempotencyKey(draft,'nonce-one')).not.toBe(createSendIdempotencyKey(draft,'nonce-two'))});
});
