import { fireEvent, render, screen } from '@testing-library/react';
import { describe, expect, it, vi } from 'vitest';
import { demoRequests } from '../demo-data';
import { PriceDecisionDialog } from './PriceDecisionDialog';

const finalDraft={status:'draft' as const,inputSemantics:'final_customer_total_tax_included' as const,enteredCustomerTotalMinor:7500,rateBasisPoints:675,serviceSubtotalMinor:7026,salesTaxMinor:474,customerTotalMinor:7500,savedAt:'2026-09-03T10:00:00Z',isCurrent:true};
const legacyDraft={status:'draft' as const,inputSemantics:'legacy_base_fare_plus_tax' as const,enteredBaseFareMinor:7495,rateBasisPoints:675,serviceSubtotalMinor:7963,salesTaxMinor:537,customerTotalMinor:8500,savedAt:'2026-09-03T10:00:00Z',isCurrent:true};

describe('manual owner quote dialog',()=>{
  it('treats the entered amount as the tax-included final price and keeps an exact $5 total unchanged',async()=>{const confirm=vi.fn(async()=>{});render(<PriceDecisionDialog request={{...demoRequests[0],quoteAmount:undefined}} busy={false} onDismiss={vi.fn()} onConfirm={confirm}/>);const price=screen.getByLabelText('Final customer price tax included');expect(price).toBeInTheDocument();expect(screen.getByLabelText('Tax rate percent')).toBeInTheDocument();fireEvent.change(price,{target:{value:'75'}});fireEvent.change(screen.getByLabelText('Tax rate percent'),{target:{value:'6.75'}});expect(screen.getAllByText('$75.00')).toHaveLength(1);expect(screen.getByText('$70.26')).toBeInTheDocument();expect(screen.getByText('$4.74')).toBeInTheDocument();fireEvent.submit(screen.getByRole('button',{name:'Save quote draft',hidden:true}).closest('form')!);expect(confirm).toHaveBeenCalledWith(expect.objectContaining({serviceSubtotalMinor:7026,salesTaxMinor:474,customerTotalMinor:7500,manualTaxQuote:expect.objectContaining({inputSemantics:'final_customer_total_tax_included',enteredCustomerTotalMinor:7500})}));});
  it('rounds only a non-multiple up to the next $5 before splitting tax',()=>{render(<PriceDecisionDialog request={demoRequests[0]} busy={false} onDismiss={vi.fn()} onConfirm={vi.fn()}/>);fireEvent.change(screen.getByLabelText('Final customer price tax included'),{target:{value:'76'}});fireEvent.change(screen.getByLabelText('Tax rate percent'),{target:{value:'0'}});expect(screen.getAllByText('$80.00')).toHaveLength(2);});
  it('rejects missing, negative, and non-finite manual input',()=>{render(<PriceDecisionDialog request={demoRequests[0]} busy={false} onDismiss={vi.fn()} onConfirm={vi.fn()}/>);const form=screen.getByRole('button',{name:'Save quote draft',hidden:true}).closest('form')!;fireEvent.submit(form);expect(screen.getByRole('alert',{hidden:true})).toHaveTextContent(/positive final customer price/i);fireEvent.change(screen.getByLabelText('Final customer price tax included'),{target:{value:'-1'}});fireEvent.change(screen.getByLabelText('Tax rate percent'),{target:{value:'Infinity'}});fireEvent.submit(form);expect(screen.getByRole('alert',{hidden:true})).toHaveTextContent(/positive final customer price/i);});
  it('reopens a final-total draft with its two owner-entered values',()=>{render(<PriceDecisionDialog request={{...demoRequests[0],quoteAmount:125,manualQuoteDraft:finalDraft}} busy={false} onDismiss={vi.fn()} onConfirm={vi.fn()}/>);expect(screen.getByText(/Draft saved/i)).toBeInTheDocument();expect(screen.getByLabelText('Final customer price tax included')).toHaveValue(75);expect(screen.getByLabelText('Tax rate percent')).toHaveValue(6.75);});
  it('keeps an historical base-fare draft visible without reusing it as a final total',()=>{render(<PriceDecisionDialog request={{...demoRequests[0],manualQuoteDraft:legacyDraft}} busy={false} onDismiss={vi.fn()} onConfirm={vi.fn()}/>);expect(screen.getByText(/historical base-fare draft/i)).toBeInTheDocument();expect(screen.getByLabelText('Final customer price tax included')).toHaveValue(null);});
});
