import {fireEvent,render,screen,waitFor} from '@testing-library/react';
import {describe,expect,it,vi} from 'vitest';
import type {RideRequest} from '../types';

vi.mock('../lib/supabase',()=>({wixPayLinkReconciliationEnabled:true}));
import {WixPaymentRecovery,wixPaymentRecoveryEligible} from './WixPaymentRecovery';

const request:RideRequest={id:'11111111-1111-4111-8111-111111111111',requestNumber:'PXR-1',status:'deposit_pending',version:4,createdAt:'2026-09-02T12:00:00Z',customerId:'c',customerName:'Guest',email:'g@example.com',phone:'2345550100',service:'airport',tripType:'One way',pickupAddress:'A',destinationAddress:'B',pickupDate:'2026-09-03',pickupTime:'13:45',passengers:1,carryons:0,checkedBags:0,hasOversizedItems:false,pricingStatus:'calculated',paymentStatus:'pending',lifecycleEffects:[{id:'link',effectType:'payment_link_creation',state:'delivered',enabledSnapshot:true,attemptCount:1,maxAttempts:4,updatedAt:'2026-09-02'},{id:'delivery',effectType:'customer_payment_link_delivery',state:'delivered',enabledSnapshot:true,attemptCount:1,maxAttempts:4,updatedAt:'2026-09-02'}]};
describe('Wix payment recovery',()=>{
  it('is visible only for a current pending request with delivered link and delivery',()=>{expect(wixPaymentRecoveryEligible(request)).toBe(true);expect(wixPaymentRecoveryEligible({...request,paymentStatus:'paid'})).toBe(false);expect(wixPaymentRecoveryEligible({...request,lifecycleEffects:request.lifecycleEffects?.slice(0,1)})).toBe(false);expect(wixPaymentRecoveryEligible({...request,version:undefined})).toBe(false)});
  it('requires an owner reason and confirmation before invoking',async()=>{const verify=vi.fn().mockResolvedValue(undefined);render(<WixPaymentRecovery request={request} onVerify={verify}/>);fireEvent.click(screen.getByRole('button',{name:/Verify Wix payment/i}));const submit=screen.getByRole('button',{name:/Verify exact payment/i});expect(submit).toBeDisabled();fireEvent.change(screen.getByLabelText(/Reason for verification/i),{target:{value:'Wix shows this exact payment completed.'}});expect(submit).toBeDisabled();fireEvent.click(screen.getByRole('checkbox'));expect(submit).toBeEnabled();fireEvent.click(submit);await waitFor(()=>expect(verify).toHaveBeenCalledWith('Wix shows this exact payment completed.'))});
  it('renders nothing for an ineligible request',()=>{const {container}=render(<WixPaymentRecovery request={{...request,status:'confirmed'}} onVerify={vi.fn()}/>);expect(container).toBeEmptyDOMElement()});
  it('shows loading and a safe error without losing the owner reason',async()=>{let rejectRequest:(error:Error)=>void=()=>{};const verify=vi.fn(()=>new Promise<void>((_resolve,reject)=>{rejectRequest=reject}));render(<WixPaymentRecovery request={request} onVerify={verify}/>);fireEvent.click(screen.getByRole('button',{name:/Verify Wix payment/i}));const reason=screen.getByLabelText(/Reason for verification/i);fireEvent.change(reason,{target:{value:'Wix receipt exists for this exact ride.'}});fireEvent.click(screen.getByRole('checkbox'));fireEvent.click(screen.getByRole('button',{name:/Verify exact payment/i}));expect(await screen.findByRole('button',{name:/Checking Wix/i})).toBeDisabled();rejectRequest(new Error('Exact Wix payment was not found.'));expect(await screen.findByRole('alert')).toHaveTextContent('Exact Wix payment was not found.');expect(reason).toHaveValue('Wix receipt exists for this exact ride.')});
});
