import {FileSearch,LockKeyhole,Upload} from 'lucide-react';
import {useState} from 'react';
import {parseHistoricalBaselineJson,validateHistoricalBaseline,type HistoricalBaselineDraft} from './historical-baseline';

const blank=():HistoricalBaselineDraft=>({cutoffDate:'',completedRides:0,starCounts:{1:0,2:0,3:0,4:0,5:0},provenance:''});

export function HistoricalBaselineReview(){
  const [draft,setDraft]=useState(blank),[reviewed,setReviewed]=useState<HistoricalBaselineDraft>(),[error,setError]=useState('');
  const changeNumber=(key:'completedRides'|1|2|3|4|5,value:string)=>setDraft(current=>key==='completedRides'?{...current,completedRides:Number(value)}:{...current,starCounts:{...current.starCounts,[key]:Number(value)}});
  async function load(file?:File){if(!file)return;setError('');try{setDraft(parseHistoricalBaselineJson(await file.text()));setReviewed(undefined)}catch(reason){setError(reason instanceof Error?reason.message:'The baseline file could not be reviewed.')}}
  function review(){const issue=validateHistoricalBaseline(draft);if(issue){setError(issue);setReviewed(undefined);return}setError('');setReviewed(structuredClone(draft))}
  return <section className="insights-card baseline-review" aria-labelledby="historical-baseline-title"><header><div><p className="eyebrow">Historical starting point</p><h2 id="historical-baseline-title">Import and review</h2></div><FileSearch aria-hidden/></header><p>Stage earlier ride and rating totals for owner review. This screen does not upload, save, or publish data.</p><label className="baseline-file"><Upload aria-hidden/><span>Load JSON for review</span><input aria-label="Historical baseline JSON" type="file" accept="application/json,.json" onChange={event=>void load(event.target.files?.[0])}/></label><div className="baseline-fields"><label><span>Cutoff date</span><input aria-label="Historical cutoff date" type="date" value={draft.cutoffDate} onChange={event=>setDraft(current=>({...current,cutoffDate:event.target.value}))}/></label><label><span>Completed rides</span><input aria-label="Historical completed rides" type="number" min="0" step="1" value={draft.completedRides||''} onChange={event=>changeNumber('completedRides',event.target.value)}/></label>{([5,4,3,2,1] as const).map(star=><label key={star}><span>{star}-star ratings</span><input aria-label={`${star}-star historical ratings`} type="number" min="0" step="1" value={draft.starCounts[star]||''} onChange={event=>changeNumber(star,event.target.value)}/></label>)}</div><label className="baseline-provenance"><span>Source and review note</span><textarea aria-label="Historical baseline provenance" rows={3} value={draft.provenance} onChange={event=>setDraft(current=>({...current,provenance:event.target.value}))}/></label>{error&&<p className="dialog-error" role="alert">{error}</p>}<button type="button" className="button secondary" onClick={review}>Review staged baseline</button>{reviewed&&<div className="baseline-readback" role="status"><strong>Review ready, not saved</strong><span>{reviewed.completedRides.toLocaleString()} completed rides through {reviewed.cutoffDate}; {Object.values(reviewed.starCounts).reduce((total,count)=>total+count,0).toLocaleString()} ratings.</span><small>{reviewed.provenance}</small></div>}<button type="button" className="button primary" disabled title="A separately approved import path is required."><LockKeyhole aria-hidden/>Import remains locked</button></section>
}
